### ISSUE TITLE
Destination: YugabyteDB

### ISSUE THREAD

**Issue by rhaegar2803** [airbytehq/connector-contest#101]
To kick things off I would like to start working on a destination connector for YugabyteDB an increasingly popular distributed database that is Postgres/SQL compatible https://www.yugabyte.com/

**Comment by RealChrisSean** [comment]
This has been assigned to you :). If you haven't started yet you may be able to use our new[ low code cdk](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/) to build this. Here's the link if you want to check it out :)

**Comment by itaseskii** [comment]
Hey @RealChrisSean I'm aware of the low code cdk since I was part of the early access program. The connector that I'm building is a destination connector and it uses a jdbc compliant driver something for which the low code cdk is not targeted towards.

**Comment by RealChrisSean** [comment]
You are correct. I totally missed this was a destination. Good luck with this one! :)

**Comment by RealChrisSean** [comment]
Hi @itaseskii how has this been going? :)

**Comment by itaseskii** [comment]
Hey @RealChrisSean I have opened a PR

**Comment by RealChrisSean** [comment]
Amazing! 🎉🎊😎

I will add this to the list of PRs to reviewed :)

**Comment by RealChrisSean** [comment]
Congrats on having this merged!

**Comment by RealChrisSean** [comment]
@itaseskii Can you please make sure your email is visible on your profile so we can contact you once we start sending payments out?

Thank you!
