### ISSUE TITLE
Source: Trino

### ISSUE THREAD

**Issue by kachontep** [airbytehq/connector-contest#103]
I would like to develop Airbyte source connector with Hive, Presto (or Trino) using PyHive (Python). Let me know if it already exists or there is an alternative connector which can be applied with this use case.

**Comment by RealChrisSean** [comment]
Go for it! :D

**Comment by RealChrisSean** [comment]
Hi @kachontep how have things been going with this? Anything we can assist you with?

**Comment by kachontep** [comment]
Hi @RealChrisSean , I am still working on it and plan to need a help from you to review it next week.

**Comment by RealChrisSean** [comment]
Awesome thanks for getting back to me so soon! :)
