### ISSUE TITLE
Source: Clockify

### ISSUE THREAD

**Issue by RobLucchi** [airbytehq/connector-contest#104]
API Docs: https://clockify.me/developers-api
@avaidyanatha I would like to work on this

**Comment by RealChrisSean** [comment]
I have assigned the ticket to you. Good luck! :)

**Comment by RealChrisSean** [comment]
Hi @RobLucchi how have things been going with this? Anything we can assist you with?

**Comment by RobLucchi** [comment]
Hello @RealChrisSean, Its been Great, Already Submitted it at https://github.com/airbytehq/airbyte/pull/17767.
I'm working on the required changes.

**Comment by RealChrisSean** [comment]
Merged. Congrats @RobLucchi :D

**Comment by RealChrisSean** [comment]
@RobLucchi Can you please make sure your email is visible on your profile so we can contact you once we start sending payments out?

Thank you!
