### ISSUE TITLE
Destination: MeiliSearch

### ISSUE THREAD

**Issue by cirdes** [airbytehq/connector-contest#105]
current version of meilisearch is not working due API changes on authorization header https://github.com/airbytehq/airbyte/issues/13076

**Comment by cirdes** [comment]
I would like to work on this!

**Comment by RealChrisSean** [comment]
Go for it. The ticket has been assigned to you :)

**Comment by RealChrisSean** [comment]
Hey @cirdes how has it been going? Anything we can help you with?

**Comment by cirdes** [comment]
@RealChrisSean , I should open a draft pull request this weekend. This feature is working but I'm struggling to write the tests. It would be great to receive some guidance.

**Comment by cirdes** [comment]
@RealChrisSean , waiting for feedbacks. https://github.com/airbytehq/airbyte/pull/18036

**Comment by RealChrisSean** [comment]
Excellent! We will get back to you within the week :).

**Comment by cirdes** [comment]
@RealChrisSean , the PR was merged https://github.com/airbytehq/airbyte/pull/18036

**Comment by RealChrisSean** [comment]
AMAZING! Congrats @cirdes :D
