### ISSUE TITLE
New Source: Braze

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/connector-contest#109]
https://www.braze.com/docs/developer_guide/home

**Comment by deveshchatuphale7** [comment]
Hey @RealChrisSean I would like to work on this one

**Comment by RealChrisSean** [comment]
Excellent good luck @deveshchatuphale7!

**Comment by RealChrisSean** [comment]
Hi @deveshchatuphale7 how are things going? Anything we can help with? :)

**Comment by deveshchatuphale7** [comment]
Hey Chris, So far I have setup local repo & started exploring Braze docs for APIs. However, I would need help in getting API Key from Braze.

**Comment by vincentkoc** [comment]
@deveshchatuphale7 @RealChrisSean if you get stuck im happy to take this on as I have access to an enterprise Braze account and would like to try the low code approach

**Comment by RealChrisSean** [comment]
Hey @deveshchatuphale7 how is it going so far with the API key? Let us know if you want @koconder to take over :). 

@koconder maybe follow up by mon or tues in case @deveshchatuphale7 doesn't reply? :)

**Comment by deveshchatuphale7** [comment]
@RealChrisSean  I think @koconder can take this issue

**Comment by RealChrisSean** [comment]
Sounds good thanks for getting back to us @deveshchatuphale7 :)

**Comment by YowanR** [comment]
@koconder Hi Vincent, is this still a contribution that you are looking to make? :)

**Comment by vincentkoc** [comment]
@YowanR more than happy to help 🚀
