### ISSUE TITLE
Source: Zapier

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#11]

**Comment by albert-marrero** [comment]
@GreeneWoods and I will work on this one! @

**Comment by RealChrisSean** [comment]
Hey @albert-marrero how's it going? Do you know if you will you use the [low-code CDK ](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/) for this? :)

**Comment by GreeneWoods** [comment]
Looking into it at this very moment, will definitely try that first!

BG
________________________________

**Comment by RealChrisSean** [comment]
Awesome! Good luck! I will label this as a low-code cdk unless you later decide to use the python cdk instead :)
