### ISSUE TITLE
New Source: Railz

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/connector-contest#110]
https://docs.railz.ai/docs

**Comment by Atharvat** [comment]
@RealChrisSean 
I am willing to work on this issue.

**Comment by RealChrisSean** [comment]
Hi @Atharvat how has this been going? :) Is there anything we can help you with?

**Comment by Atharvat** [comment]
Hi @RealChrisSean sorry for the delay. I am working on it, will create a PR soon
