### ISSUE TITLE
New Source: Zoom

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/connector-contest#111]

**Comment by subhamX** [comment]
Hi @RealChrisSean, could you please share what data specifically we want to import from the `Zoom Source`?

**Comment by chandanpatra2111** [comment]
Hi @RealChrisSean ,could you please provide the description?

**Comment by YowanR** [comment]
@misteryeo Can you help here? I can't access the original asana task. The best I have right now is this: https://github.com/airbytehq/airbyte/issues/3696.

**Comment by YowanR** [comment]
Hello everyone! Let me try to bring a little bit of clarity and direction here. We would ideally want to have parity with the docs described [here](https://docs.airbyte.com/integrations/sources/zoom/). Does this make sense? This connector was originally Singer-based but now, we want to move it to our low-code framework and it seems easier to write it from scratch than migrate it. Original code can be found [here](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/source-zoom-singer/source_zoom_singer) for reference.

**Comment by subhamX** [comment]
@RealChrisSean may I take this issue? It will help me gain better insights into the low-code cdk. I do have [another issue assigned](https://github.com/airbytehq/connector-contest/issues/117), but we're still missing some clarity with the approach. Let me take this one meanwhile?

**Comment by RealChrisSean** [comment]
Sure go for it @subhamX :). Good luck!

**Comment by RealChrisSean** [comment]
Hi @subhamX how has this been going? Did you get the help you need?

**Comment by subhamX** [comment]
@RealChrisSean;

The implementation part is almost done. I've tested the free APIs, but testing the PRO features is tricky (as I don't have Zoom PRO, and it's very expensive 😅). 

I've reached out to a few folks at Zoom, and their DevRel team might reply back soon. (in case they're interested in providing Zoom PRO for a day).

Also, I had a small query on the design approach (and error_handling), and we're currently discussing [here on airbytehq slack](https://airbytehq.slack.com/archives/C0450PCSDB2/p1665997441426699?thread_ts=1665569372.781649&cid=C0450PCSDB2). 

Hopefully, in a few days, I shall make the PR. Please let me know if you have any suggestions or anything in general 🙂.

**Comment by RealChrisSean** [comment]
Congrats on having this merged!

**Comment by RealChrisSean** [comment]
https://github.com/airbytehq/airbyte/issues/17772

**Comment by RealChrisSean** [comment]
@subhamX Can you please make sure your email is visible on your profile so we can contact you once we start sending payments out?

Thank you!

**Comment by subhamX** [comment]
@RealChrisSean Done;
