### ISSUE TITLE
New Source: InStatus

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/connector-contest#112]

**Comment by AP2008** [comment]
I would like to work on this. Please assign it to me.

**Comment by RealChrisSean** [comment]
This has been assigned to you :)

**Comment by pabloescoder** [comment]
@AP2008 Have you started to / are you still working on this? If not, then can I take this issue? @RealChrisSean

**Comment by Limits0x** [comment]
> @AP2008 Have you started to / are you still working on this? If not, then can I take this issue? @RealChrisSean 

Yeah. I have started working on this. I'll be making a PR in the next few days.

**Comment by pabloescoder** [comment]
> > @AP2008 Have you started to / are you still working on this? If not, then can I take this issue? @RealChrisSean
> 
> Yeah. I have started working on this. I'll be making a PR in the next few days.

Alright, sounds good!

**Comment by RealChrisSean** [comment]
> > @AP2008 Have you started to / are you still working on this? If not, then can I take this issue? @RealChrisSean 
> 
> Yeah. I have started working on this. I'll be making a PR in the next few days. 

Amazing!
