### ISSUE TITLE
New Source: Moengage

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/connector-contest#113]
https://developers.moengage.com/hc/en-us

**Comment by sjha2048** [comment]
I would like to pick this up

**Comment by RealChrisSean** [comment]
Awesome! Good luck :)

**Comment by sjha2048** [comment]
Hey @RealChrisSean I explored MoEngage APIs today and all the APIs to retrieve data in zip format and on CDKs development website I saw this as a requirement
>>Does the REST API documentation show which HTTP method to use to retrieve data, and that the response is a JSON object?

I wanted to ask if this would be feasible or not.

**Comment by RealChrisSean** [comment]
This is a good question. I dont think this will work with the low-code cdk. I totally missed that. The python cdk might be best for this. Sorry about that.
