### ISSUE TITLE
New Source: Gorgias

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/connector-contest#115]
https://github.com/airbytehq/airbyte/issues/2940

**Comment by sohailgi** [comment]
I would like to work on this. I am completely a newbie,can you help me with this?

**Comment by RealChrisSean** [comment]
Hello @sohailgi we have a getting started guide [here](https://docs.airbyte.com/connector-development/config-based/tutorial/getting-started). 

We also have a [video tutorial ](https://www.youtube.com/watch?v=i7VSL2bDvmw) that you can watch. Part 2 will go live on Monday :).

If you join our slack channel, two of our engineers are offering a 30-minute 1-on-1 session every week (during hacktober) to help guide anyone with their connector. You can join the #hacktobestfest-2022 slack channel [here](https://app.slack.com/accept-shared-channel/T02TET08MDH/I043WFREPQX/enQtNDEzMjUzNTQ5OTg0Ny0xN2I2MDU4NGFkOTNlYzZlN2JmMGIzOTgyMjU1ODk1MDIzZWM5YTAzMThkMDFkNzgzNWNjNzljOGU1MmRhMDIw).

Please let me know if that helps :). I have also assigned the issue to you. If you have anymore questions you can DM me directly on slack :).

**Comment by sohailgi** [comment]
I want more help into this,I've messaged you on slack

**Comment by RealChrisSean** [comment]
@sohailgi did you get the help you need? :)

**Comment by sohailgi** [comment]
https://github.com/airbytehq/airbyte/pull/18951

Pull request added
