### ISSUE TITLE
New Source: GraphQL API

### ISSUE THREAD

**Issue by subhamX** [airbytehq/connector-contest#117]
It is one of the popular connectors requested by around 180+ folks. (Ref: https://airbyte.com/connector-requests).

I think we should support all the standard GraphQL Object fields, namely the following: (Ref: https://graphql.org/learn/schema/)
```
Int
Float
String
Boolean
ID
```

In short, the user needs to specify the custom graphql query, frequency of data fetch, and the graphql server's endpoint.

I'm not sure about the **authentication**, though. Maybe we can go with Bearer Authentication?

Please let me know (and assign me) if the above plan makes sense. I trust that it shouldn't take a lot of time. :)

**Comment by RealChrisSean** [comment]
Hey @subhamX this looks great! Just to confirm you will attempt this with our [low-code cdk](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/)? :)

**Comment by josix** [comment]
This would be really helpful for the usage of Graph API. Looking forward to it!

**Comment by subhamX** [comment]
@RealChrisSean;
> Just to confirm you will attempt this with our [low-code cdk](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/)?

I don't think it's possible to do it with low-code cdk. I think we need to have schema (aka catalog) of the data source to use the `low-code cdk`. But here, we're building a solution for all the servers, so we don't know beforehand.

Is it possible to define the AirbyteCatalog dynamically? (I think the CDK was never meant for this purpose.) Also, it will be prone to errors.

Feel free to correct me if I'm wrong.

Maybe for now I can take https://github.com/airbytehq/connector-contest/issues/111 issue, and then work on this one?

**Comment by RealChrisSean** [comment]
Yes of course. Thanks for asking in advance. :)

**Comment by Dynnammo** [comment]
At my company, we would be very interested to develop a connector for the GraphQL of our OSS software (source code [here](https://github.com/decidim/decidim)). If it seems consistent, we have some time to work on it in the next weeks, and would be glad to help on a draft PR.

**Comment by subhamX** [comment]
That's awesome @Dynnammo; 

I'm currently working on #111 and in case you want, feel free to take lead on this issue. (I will be hanging around though. 😉)

> Maybe a first step would be to work on a specific GraphQL source to see how it could work knowing the schema in advance, and then move on to generalization?

1. I think we should ask the user for `graphql server URL`. 
2. Then, run an introspection query to get all the schemas. 
3. We will have a one-on-one mapping from `schemas (graphql)` to `streams (airbyte)`. 
4. Finally ask the user to select which schemas/streams they want to store. 

I'm yet to explore `python CDK`. So I'm not sure how to do step 3. Rest all looks okay.

**Comment by RealChrisSean** [comment]
You are so kind @subhamX!  @Dynnammo can you please confirm if you can take this issue and complete it before the hackathon deadline on 11/02/22? :D. I will assign it to you if so. Thanks!

**Comment by Dynnammo** [comment]
> You are so kind @subhamX! @Dynnammo can you please confirm if you can take this issue and complete it before the hackathon deadline on 11/02/22? :D. I will assign it to you if so. Thanks!

Honestly, doing the all thing in 1 month seems short, starting from scratch as for me. However, since we're condemned to do it in our business, don't hesitate to assign me anyway, I'll see if we can speed up by peer-working on it with @subhamX .

**Comment by RealChrisSean** [comment]
Good luck! I will assign this to both of you :)

**Comment by RealChrisSean** [comment]
Good luck! I will assign this to both of you :)
