### ISSUE TITLE
New Source: Azure Blob Storage

### ISSUE THREAD

**Issue by parinzee** [airbytehq/connector-contest#118]
This is also a very popular connector that has been requested by a lot of people [here](https://airbyte.com/connector-requests).

I believe the implementation would be quite similar to the **[AWS S3 connector](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/destination-s3)**!

If you guys accept this, please assign me the issue and I'll take it on right away. I think this shouldn't take that much time!

**Comment by parinzee** [comment]
@RealChrisSean For extra technical information, I will try to use the low-code CDK first, since it looks really cool, but if that doesn't work I'll divert to the Python CDK!

Thank you for your time!

**Comment by RealChrisSean** [comment]
Perfect! Good luck on this! :)

**Comment by RealChrisSean** [comment]
Hey @parinzee how has it been going for you? Are you still pursuing this with our low-code cdk? :)

**Comment by parinzee** [comment]
Hey @RealChrisSean! Sorry for the confusion, I'm using the Python CDK since there is an Azure SDK available. I'm just finishing up on the source-acceptance tests right now. Could I ask if unit-tests are nescesscary? Since the source-acceptance tests already tests all the functionality of the source.

Thank you very much!

**Comment by RealChrisSean** [comment]
Excellent! No need to apologize as well. 

Yes, it is still necessary :(.

**Comment by parinzee** [comment]
Fantastic, thank you for the info!
