### ISSUE TITLE
New Source: Auth0

### ISSUE THREAD

**Issue by YiyangLi** [airbytehq/connector-contest#119]
I'll work on this one!

**Comment by RealChrisSean** [comment]
Awesome! This has been assigned to you :)

**Comment by RealChrisSean** [comment]
Hi, @YiyangLi just asking for tracking purposes, will you be using the [low-code CDK ](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/) for this?

**Comment by YiyangLi** [comment]
@RealChrisSean Yes, I am working on it. AND I am using the low-code CDK. 

I have a question, according to the requirements, `Check that all critical streams have been implemented.` How many streams I have to add? Thanks.

**Comment by RealChrisSean** [comment]
Hey, @YiyangLi I have an answer, but I will clarify this really quick before giving you a proper response. I'll get back to you by tomorrow at the latest :)

**Comment by RealChrisSean** [comment]
Also excellent! I'm happy to hear that you're trying out our low-code cdk :)

**Comment by RealChrisSean** [comment]
Congrats on having this merged :D
