### ISSUE TITLE
Source: Jira Server

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#12]

**Comment by avaidyanatha** [comment]
Also @grumpy-miner, make sure to evaluate the differences between the Jira source and this source. I'm unsure of the complexity, but there might be some reusable code here. https://docs.airbyte.io/integrations/sources/jira

**Comment by grumpy-miner** [comment]
@avaidyanatha thanks 🙌 . 
I'm aware of some differences, as far as I remember the biggest differences are in the fields that Jira api v2 is returning. Endpoints should be more or less similar as for v3 but of course I will investigate it before implementation.
