### ISSUE TITLE
New source: Google Play

### ISSUE THREAD

**Issue by masyagin1998** [airbytehq/connector-contest#120]
Hello, Airbyte!

I'd like to work on Google Play connector, which can sync selected app reviews.
It supports filtering by languages and countries of reviews and can work in full refresh/natural increment modes.

It doesn't need any API Key, because it uses direct Google Play website with little parsing.
I've talked about it here https://airbyte.com/blog/how-airbytes-reliable-ready-to-use-data-pipelines-sped-up-anecdotes-launch-and-growth and in Slack, and now I'm going to finally push it to open-source.

I think, it would be easier to implement it with Python HTTP Source SDK.

**Comment by masyagin1998** [comment]
@misteryeo
You said in Slack that I can tag You, when I start to work on connectors.

**Comment by misteryeo** [comment]
In future, can you please tag @RealChrisSean please @masyagin1998!

Just curious, why do you think it would be easier to implement with the Python HTTP Source SDK?

**Comment by masyagin1998** [comment]
Okay, I'll tag him in next messages not You (just tagged You because of our talk in direct messages in Slack on 7th September).

I think usage of Python HTTP Source SDK is easier, because I need to process raw HTMLs and it can't be done easily with Low-code SDK

**Comment by masyagin1998** [comment]
I won't write in other issues to skip next possible message duplicates

**Comment by RealChrisSean** [comment]
This has been assigned to you :D

**Comment by RealChrisSean** [comment]
How has it been going @masyagin1998? Anything we can help with? :)

**Comment by masyagin1998** [comment]
Hey, @RealChrisSean !
I'm working on Trustpilot right now: https://github.com/airbytehq/airbyte/pull/17933 and going to fix all points of review this week.
Then I'll work on Google Play)
