### ISSUE TITLE
New source: AppStore

### ISSUE THREAD

**Issue by masyagin1998** [airbytehq/connector-contest#121]
Hello, Airbyte!

I'd like to work on AppStore connector, which can sync selected app reviews.

In fact I'm going to write two AppStore connectors: one for RSS and one for AMP API. First is fast and incremental but has limits: no more than 500 last records. Second is slow and can't work in natural incremental mode but is able to sync all AppStore reviews.

I've talked about it here https://airbyte.com/blog/how-airbytes-reliable-ready-to-use-data-pipelines-sped-up-anecdotes-launch-and-growth and in Slack, and now I'm going to finally push it to open-source.

I think, it would be easier to implement it with Python HTTP Source SDK.

**Comment by masyagin1998** [comment]
@misteryeo
You said in Slack that I can tag You, when I start to work on connectors.

**Comment by misteryeo** [comment]
Looping in @RealChrisSean.

@masyagin1998 how is this different from the Appstore connector we already have today: https://docs.airbyte.com/integrations/sources/appstore/?

**Comment by masyagin1998** [comment]
Current AppStore connector gives ability to track and save private App information like Sales, Subscriptions etc.
I'm talking about public information like reviews, scores etc.

**Comment by RealChrisSean** [comment]
Hello @masyagin1998 sounds good. Please work on one connector at time (per [guidelines](https://airbyte.com/connector-contest)). The other one will be easier to work on so maybe work on that one first? :) Please tag me when you start working on this one so that I can assign this issue to you later. Thanks! :)

**Comment by misteryeo** [comment]
@masyagin1998 I'd like to encourage you to build the low code CDK version of the **existing AppStore connector** and then adding the missing functionality you've described. We'd want to have a single connector with expanded functionality rather than having separate connectors. Would that work?

**Comment by masyagin1998** [comment]
@misteryeo Yeah, I think, it should work!
Try to do it right after completing Trustpilot connector.
