### ISSUE TITLE
New source: Status Hero

### ISSUE THREAD

**Issue by coder46** [airbytehq/connector-contest#123]
Hi Airbyte !

I'd like to make a connector for Status Hero (https://statushero.com/). This tool is used by remote dev teams to record daily check-ins/standups.

I'll probably first support the `statuses` endpoint which I think can be used as part of a pipeline that runs at the end of a day and enables the user to "download" status updates for their team and do some post-processing on it

**Comment by RealChrisSean** [comment]
Go for it! This has been assigned to you.

**Comment by RealChrisSean** [comment]
Hi, @coder46 will you be using the [low-code CDK ](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/) with this? :)
