### ISSUE TITLE
Destination: CockroachDB

### ISSUE THREAD

**Issue by alrz1999** [airbytehq/connector-contest#124]
I'll work on this one!

**Comment by RealChrisSean** [comment]
Hi, @alrz1999! How has it been? Will you use the [low-code CDK ](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/) with this? :)

**Comment by RealChrisSean** [comment]
Hey @alrz1999 just following up on this :). Is there anything we can help with?
