### ISSUE TITLE
New Source: Datadog

### ISSUE THREAD

**Issue by mmolimar** [airbytehq/connector-contest#125]
Hey!

I'd like to start building a source connector for [Datadog](https://docs.datadoghq.com/api/latest/).

**Comment by RealChrisSean** [comment]
Nice! Good luck! This has been assigned to you.

**Comment by RealChrisSean** [comment]
Hi, @mmolimar will you be using the [low-code CDK ](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/) for this? :)

**Comment by mmolimar** [comment]
I used the normal CDK.
Just created [a PR](https://github.com/airbytehq/airbyte/pull/18150)!

**Comment by RealChrisSean** [comment]
Amazing!!!
