### ISSUE TITLE
New Source : Zendesk Sell

### ISSUE THREAD

**Issue by alexchouraki** [airbytehq/connector-contest#126]
Hello!

I'd like to build a source connector for [Zendesk Sell](https://developer.zendesk.com/api-reference/sales-crm/introduction/).

**Comment by RealChrisSean** [comment]
Perfect! This has been assigned to you :)

**Comment by RealChrisSean** [comment]
AWESOME!!! @alexchouraki

**Comment by RealChrisSean** [comment]
Congrats on having this merged @alexchouraki :D

**Comment by RealChrisSean** [comment]
@alexchouraki Can you please make sure your email is visible on your profile so we can contact you once we start sending payments out?

Thank you!
