### ISSUE TITLE
New source: Waiteraid

### ISSUE THREAD

**Issue by sbrickel-nimble** [airbytehq/connector-contest#127]
Hi Airbyte,

I require a connector for Waiteraid, a booking system for restaurants.
The extracted data (table reservation, customer data, etc) will be helpful for optimization and marketing purposes.

**Comment by RealChrisSean** [comment]
Excellent! This issue has been assigned to you :)

**Comment by RealChrisSean** [comment]
Hi, @sbrickel-nimble! How has it been going for you? Anything we can help you with? Will you be using the [low-code CDK ](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/) for this? :) If not I will label this with the python cdk thanks!

**Comment by ghost** [comment]
Hi @RealChrisSean, thanks for asking. Yes, I am using the low-code CDK. My current issue is with my login data to the platform, so unrelated to the connector. I am in communication with the responsible people and hope to solve this issue quickly

**Comment by ghost** [comment]
Hi @RealChrisSean,

now I am having issues and could use some help. I already posted in the Slack group, but don't have the best experience in getting answers there.
https://airbytehq.slack.com/archives/C021JANJ6TY/p1666179654154549

**Comment by RealChrisSean** [comment]
https://github.com/airbytehq/airbyte/pull/18165

**Comment by RealChrisSean** [comment]
MERGED! Congrats @sbrickel-nimble

**Comment by RealChrisSean** [comment]
@sbrickel-nimble can you please update your GitHub account where it will show your email on your profile so we can send you the proper payment once we sent out everyone's prizes? Thanks!

**Comment by ghost** [comment]
> 

My email address is now public.

**Comment by RealChrisSean** [comment]
Awesome :)

**Comment by RealChrisSean** [comment]
Hi @sbrickel-nimble for some reason I can't see your email on your profile. Can you please DM me on slack with a link to this issue? :) I will make sure to add it on the list then. 

Thanks!
