### ISSUE TITLE
New Source: Mailerlite

### ISSUE THREAD

**Issue by rytismi** [airbytehq/connector-contest#128]
Hello,

I'd like to build a connector for [Mailerlite](https://developers.mailerlite.com/).

**Comment by RealChrisSean** [comment]
Go for it. Good luck @rytismi :D

**Comment by RealChrisSean** [comment]
Hi, @rytismi will you use the [low-code CDK ](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/) for this? :)

**Comment by rytismi** [comment]
Yes @RealChrisSean :)

**Comment by RealChrisSean** [comment]
Excellent! Good luck!

**Comment by rytismi** [comment]
Opened a PR: https://github.com/airbytehq/airbyte/pull/18336

**Comment by RealChrisSean** [comment]
Amazing! 

Our team should get back to you sometime next week. :)

**Comment by RealChrisSean** [comment]
Congrats on having this merged!
