### ISSUE TITLE
Source: ServiceNow

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#13]

**Comment by NightHack36** [comment]
can you assign me please and explian please, how to work on this issue

**Comment by RealChrisSean** [comment]
Hello @NightHack36, I assigned one ticket to you before this. Please work on one connector at a time. Thank you :D

**Comment by btkcodedev** [comment]
@RealChrisSean  
Can I work on this issue?
I am a beginner. But I will try.

**Comment by RealChrisSean** [comment]
Yes go for it!

**Comment by btkcodedev** [comment]
Thanks :)

**Comment by btkcodedev** [comment]
@RealChrisSean Just wanted to know that, could I only focus on email end point only? BCZ it has tons of endpoints🔚
