### ISSUE TITLE
New Source: Youtube

### ISSUE THREAD

**Issue by NoelJacob** [airbytehq/connector-contest#130]
Get data and statistics from your channel. I would like to work on this.

**Comment by Rahul-Kumar-prog** [comment]
Hey @NoelJacob, Rahul this side actually I was exploring connectors and learned about them and now I would like to contribute to building connectors. I saw that all connectors are assigned if you don't mind can i work on this issue and create a youtube connector? i really want to working on it.
or, we both can work together on it? if you don't mind.

**Comment by NoelJacob** [comment]
@Rahul-Kumar-prog  Sorry, I've started and am in the middle of it. I'm looking for an official go ahead from @RealChrisSean

**Comment by RealChrisSean** [comment]
@NoelJacob this has been assigned to you :D.

**Comment by Rahul-Kumar-prog** [comment]
@NoelJacob no worry its ok

**Comment by RealChrisSean** [comment]
Hi @NoelJacob will you be using the [low-code cdk ](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/) for this? :)

**Comment by NoelJacob** [comment]
Yes I'm using low code

**Comment by RealChrisSean** [comment]
Awesome! Good luck! :)
