### ISSUE TITLE
New Source: Ashby

### ISSUE THREAD

**Issue by elliottrabac** [airbytehq/connector-contest#131]
Hi Airbyte!

I'd like to make a connector for Status Ashby (https://developers.ashbyhq.com/reference/introduction).
This tool is an ATS platform used by many companies.

Can I work on it in for the contest?

**Comment by RealChrisSean** [comment]
Yes go for it! :D Good luck @elliottrabac!

**Comment by RealChrisSean** [comment]
Hi, @elliottrabac will you be using the [low-code CDK ](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/) for this? :)

**Comment by elliottrabac** [comment]
Yes, very excited to see how it goes!

**Comment by RealChrisSean** [comment]
Excellent! Good luck! :)

**Comment by elliottrabac** [comment]
PR submitted ✅

**Comment by RealChrisSean** [comment]
Niiice!

**Comment by RealChrisSean** [comment]
Congrats on having this merged @elliottrabac!

**Comment by RealChrisSean** [comment]
@elliottrabac Can you please make sure your email is visible on your profile so we can contact you once we start sending payments out?

Thank you!

**Comment by elliottrabac** [comment]
Done ✅
