### ISSUE TITLE
New Source: Shopify Partner

### ISSUE THREAD

**Issue by ctrlaltdylan** [airbytehq/connector-contest#132]
There's an existing Shopify connector, but not for the separate Shopify Partner API. This API is available to Shopify app developers, theme designers and Experts.

https://shopify.dev/api/partner

**Comment by ctrlaltdylan** [comment]
I've written the Shopify Partner connector for Pipedream, would like to try my hand at building an Airbyte connector :)

**Comment by RealChrisSean** [comment]
Hello @ctrlaltdylan this has been assigned to you. Go for it and good luck! :D

**Comment by RealChrisSean** [comment]
Hi, @ctrlaltdylan will you use the [low-code CDK ](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/) for this? :)

**Comment by ctrlaltdylan** [comment]
@RealChrisSean - I would but there's only a GraphQL endpoint for it. The low-code CDK is designed for REST APIs right?

**Comment by RealChrisSean** [comment]
@ctrlaltdylan yes you are correct. Thanks for clarifying! :)
