### ISSUE TITLE
New Source: Gridly

### ISSUE THREAD

**Issue by hntan** [airbytehq/connector-contest#133]
Hi Airbyte team!
I'm a java backend developer, I'm currently working for [Gridly](https://www.gridly.com/). I would like to add Gridly as a new source connector.

**Comment by RealChrisSean** [comment]
Go for it! Good luck @hntan! :D

**Comment by RealChrisSean** [comment]
Hi @hntan did you plan on using our [low-code cdk](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/) for this?

**Comment by hntan** [comment]
Hi @RealChrisSean, the Gridly Api doesn't follow the pagination mechanisms which are described in the low-code cdk unfortunately. So I'll use the python cdk instead.

**Comment by RealChrisSean** [comment]
Hi @hntan thank you for clarifying. Good luck with this :)

**Comment by hntan** [comment]
Pull request is created [18342](https://github.com/airbytehq/airbyte/pull/18342), please review it. cc @RealChrisSean

**Comment by RealChrisSean** [comment]
Amazing! The team will get back to you next week since everyone is off during the weekend. :)
