### ISSUE TITLE
New Source: Anilist 

### ISSUE THREAD

**Issue by eigengravy** [airbytehq/connector-contest#135]
[Anilist](https://anilist.co/)
[Anilist Developer Docs](https://anilist.gitbook.io/anilist-apiv2-docs/)
Is there support for GraphQL based APIs?

**Comment by marcosmarxm** [comment]
btw amazing suggestion!

**Comment by RealChrisSean** [comment]
@eigengravy did you plan on working on this issue? :)

**Comment by Smartmind12** [comment]
@RealChrisSean Can i start working on this issue??

**Comment by RealChrisSean** [comment]
Yes! I have assigned this issue to yo. Good luck!
