### ISSUE TITLE
New Source: Trakt

### ISSUE THREAD

**Issue by jay-tau** [airbytehq/connector-contest#136]
Using [Trakt](https://trakt.tv) as a source for Airbyte.

**Comment by marcosmarxm** [comment]
Do you want me to assign this to you @jay-tau ?

**Comment by RealChrisSean** [comment]
Hi, @jay-tau will you use the [low-code CDK ](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/) for this? :)

**Comment by jay-tau** [comment]
Hi, if I do work on this, I will try to use the low-code CDK. At the moment, I am unsure if I can get it working, but don't mind trying

**Comment by RealChrisSean** [comment]
Awesome! Please let us know if there's anything we can help with :).
