### ISSUE TITLE
New Source: TMDb

### ISSUE THREAD

**Issue by jay-tau** [airbytehq/connector-contest#137]
I would like to work on this

**Comment by RealChrisSean** [comment]
Hello @jay-tau this has been assigned to you.

**Comment by RealChrisSean** [comment]
Hi, @jay-tau will you use the [low-code CDK ](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/) for this? :)

**Comment by jay-tau** [comment]
I am trying to use the low-code CDK for this

**Comment by RealChrisSean** [comment]
Excellent!

**Comment by btkcodedev** [comment]
@RealChrisSean If the assignee is busy, I could work on it.
Could you please make an update with this issue?

**Comment by RealChrisSean** [comment]
Hey @jay-tau how is it going so far? Is there anything we can help with?

@btkcodedev Please correct me if I'm wrong, but I believe you are working on another connector at the moment. If not, in case jay is busy and doesn't get back to us within 24 hours you can take this over.

**Comment by jay-tau** [comment]
I am having some trouble. I think it would be better if @btkcodedev picks up this issue.

**Comment by btkcodedev** [comment]
@jay-tau Thanks
@RealChrisSean Please assign this to me

**Comment by RealChrisSean** [comment]
Thanks for getting back to us so quickly @jay-tau. I have assigned this to you @btkcodedev

**Comment by btkcodedev** [comment]
@RealChrisSean Update: PR merged successfully!
Thanks for the support

**Comment by btkcodedev** [comment]
Please tag me here for any further information
