### ISSUE TITLE
New Source : IMDb

### ISSUE THREAD

**Issue by CapedBaldie** [airbytehq/connector-contest#139]

**Comment by CapedBaldie** [comment]
I would like to work on this.

**Comment by RealChrisSean** [comment]
Hi @CapedBaldie this has been assigned to you.

**Comment by RealChrisSean** [comment]
Hi, @CapedBaldie will you use the [low-code CDK ](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/) for this? :)
