### ISSUE TITLE
New Source: Monzo

### ISSUE THREAD

**Issue by imrehg** [airbytehq/connector-contest#141]
An UK neobank. API docs: https://docs.monzo.com/

**Comment by RealChrisSean** [comment]
Hello @imrehg this has been assigned to you. Good luck!

**Comment by RealChrisSean** [comment]
Hi, @imrehg will you use the [low-code CDK ](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/) for this? :)

**Comment by imrehg** [comment]
@RealChrisSean I'm hoping to, depends on sorting out the authentication mainly, and I got some help regarding that on the Airbyte Slack, so the first stab is with low-code indeed.

**Comment by RealChrisSean** [comment]
Awesome! I'm happy to hear you received help on slack as well ).

**Comment by imrehg** [comment]
Authentication continues to be a pain, as trying to see examples whether AirByte can do the full OAuth 2.0 redirect game that Monzo needs. Alternatively also checking if AirByte uses the refresh tokens that can be potentially provided in some not-so-nice manual way.

In the meantime I've picked up an easier-to-handle neobank, #146
