### ISSUE TITLE
New Source: Gutendex

### ISSUE THREAD

**Issue by pabloescoder** [airbytehq/connector-contest#143]
Web-API for fetching Books' Metadata from the Project Gutenberg Books Library
API Docs: https://gutendex.com/

I would like to work on this!

**Comment by RealChrisSean** [comment]
Excellent! This has been assigned to you :). Will you be using the low-code cdk for this?

**Comment by pabloescoder** [comment]
@RealChrisSean Thank you! :D 
Yes I will be using the low-code cdk for this.

**Comment by RealChrisSean** [comment]
Excellent!!! :)

**Comment by pabloescoder** [comment]
@RealChrisSean Could you please add the **complete** label to this issue since the PR I made for it has been merged? :D

**Comment by RealChrisSean** [comment]
CONGRATS!!!! WOOOOO! :)

**Comment by RealChrisSean** [comment]
Closing as complete

**Comment by RealChrisSean** [comment]
Congrats :)

**Comment by pabloescoder** [comment]
> Congrats :)

Thank you!! :D

**Comment by RealChrisSean** [comment]
Hi @pabloescoder is the email on your profile the one you want to use to be paid via Paypal?

**Comment by pabloescoder** [comment]
Hey @RealChrisSean! My PayPal email id is different. Should I send it to you on Slack?

**Comment by RealChrisSean** [comment]
Yes please. Please DM me on slack with a link to this issue :).

**Comment by pabloescoder** [comment]
Sure, will do that right away. Thank you!

**Comment by pabloescoder** [comment]
@RealChrisSean I've messaged you on Slack with my PayPal email id and I've also updated my GitHub profile to show my PayPal email id.
