### ISSUE TITLE
New Source: Starling Bank

### ISSUE THREAD

**Issue by imrehg** [airbytehq/connector-contest#146]
Docs: https://developer.starlingbank.com/docs

**Comment by imrehg** [comment]
Made some initial progress as a low-code CDK solution, pulling accounts and balances with a personal access token (work [on this branch](https://github.com/imrehg/airbyte/tree/source-starling-bank)).

**Comment by Smartmind12** [comment]
@imrehg Can you assign this to me ...thanks!

**Comment by imrehg** [comment]
I cannot change assignments, if you think implementing this source is relevant for you, just go ahead with it!

**Comment by RealChrisSean** [comment]
@Smartmind12 I have assigned this to you :)
