### ISSUE TITLE
New Source: Sailthru

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/connector-contest#148]

**Comment by Sid-Lais** [comment]
I find this connector competition interesting and would like to take part but I'm a beginner. Can this be done by low code CDK? Also where can I find the API key.

**Comment by RealChrisSean** [comment]
Hello @Sid-Lais sorry for the late response. I have not had a chance to check out their API. You can check if this is low-code compatible here: https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview

**Comment by Sid-Lais** [comment]
It's okay. I got assigned to another issue. Will be working on that for now.

**Comment by RealChrisSean** [comment]
Sounds good! Good luck with that one :)

**Comment by sandeepB3** [comment]
Hey!! I would like to work on this, I am new to making connectors but I will try my best. Can I be assigned?

**Comment by RealChrisSean** [comment]
Hi @sandeepB3 I have assigned this issue to you :). Good luck!

**Comment by sandeepB3** [comment]
Okay, Thank you!

**Comment by sandeepB3** [comment]
Hey @RealChrisSean I explored the Sailthru Website & its API documentation. Sailthru provides a business solution for companies. Hence it is not available for open source testing according to my findings.

**Comment by RealChrisSean** [comment]
Nooooo. I will double-check with the team thank you so much for letting us know.
