### ISSUE TITLE
New source: DynamoDB

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/connector-contest#149]

**Comment by itaseskii** [comment]
DynamoDB is one of the connectors that I wanted to work on during the hackathon and I would like to work on this next. @RealChrisSean please assign it to me.

**Comment by RealChrisSean** [comment]
@itaseskii amazing! I have assigned this ticket to you. :) Will you attempt to use the low-code cdk for this as well? 😇

**Comment by itaseskii** [comment]
Dynamodb is an AWS NoSQL database and is not meant to be integrated with using the low-code-cdk. I will be using the AWS sdk for Java.

**Comment by techytushar** [comment]
Hey @itaseskii ,
Since you already have other issues assigned to you, can I pick this one up ?

**Comment by itaseskii** [comment]
Hey @techytushar, no, I'm actively working on this. What other issues are you referring to?

**Comment by techytushar** [comment]
I am referring to this issue https://github.com/airbytehq/connector-contest/issues/144

**Comment by itaseskii** [comment]
The task that you are referring to is an enhancement to an existing connector and was part of an internal agreement :)
