### ISSUE TITLE
New source: Lokalise

### ISSUE THREAD

**Issue by money8203** [airbytehq/connector-contest#150]

**Comment by RealChrisSean** [comment]
Thanks for creating this issue @money8203! :) Have you had a chance to check if their API is [low-code cdk ](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/)compatible? :)

**Comment by money8203** [comment]
Welcome !
Yea it is compatible.

If you like I can keep finding the missing sources and issue them from time to time :)

**Comment by deanmalan** [comment]
Since I've created a PR for #19, I'm happy to get started on this one :)

**Comment by RealChrisSean** [comment]
@money8203 you are amazing. Thank you for the help! 🙏

**Comment by RealChrisSean** [comment]
@delenamalan amazing! Good luck with this one :)

**Comment by money8203** [comment]
@RealChrisSean Anytime bro !
If you like my work ,make me a member of your community I will be more than happy to be a part of something greater than me :)

**Comment by RealChrisSean** [comment]
We are only as great as our community. 🙏

**Comment by RealChrisSean** [comment]
Amazing! Congrats @delenamalan how was it working with the low-code cdk?
