### ISSUE TITLE
New Source: Quip

### ISSUE THREAD

**Issue by money8203** [airbytehq/connector-contest#152]

**Comment by RealChrisSean** [comment]
Hi @money8203 this has been assigned to you. Will you be using the low-code CDK for this? :)

**Comment by money8203** [comment]
Thanks @RealChrisSean for counting on me but I'm sorry, please assign this task to someone else because i'm just a beginner and working on previous one so it will take a little time for me to complete one project and by doing so someone will have their chance to contribute , but don't worry i will keep contributing to issues whenever I will find any low code cdk application or anything related to project :)

**Comment by RealChrisSean** [comment]
Thank you for letting me know :). Good luck!

**Comment by btkcodedev** [comment]
@RealChrisSean I've gone through this but the api is not open source I think.
It requires license for api testing.

**Comment by RealChrisSean** [comment]
NOOO So sorry. Thank you for checking @btkcodedev
