### ISSUE TITLE
New Source: JFrog Artifactory

### ISSUE THREAD

**Issue by money8203** [airbytehq/connector-contest#153]

**Comment by BajajAyush** [comment]
please assign it to me

**Comment by RealChrisSean** [comment]
Hello @BajajAyush you can only work on one connector at time. I have assigned a ticket to you but you can move to this when you're done with the other one :)

**Comment by Bisht13** [comment]
Can I be assigned to this?

**Comment by RealChrisSean** [comment]
Hello I have assigned this to you @Bisht13
