### ISSUE TITLE
New source: PyPI

### ISSUE THREAD

**Issue by recursiveforte** [airbytehq/connector-contest#154]

**Comment by RealChrisSean** [comment]
Hi @recursiveforte thank you for creating this issue :). Did you want me to assign this to you? If so, will you be using the low-code cdk as well? :)

**Comment by recursiveforte** [comment]
Yes, I was going to work on it. I'll be using the low-code CDK.

**Comment by RealChrisSean** [comment]
Perfect! 🎉😎

I will assign this to you. Good luck! 🤞🏼

**Comment by recursiveforte** [comment]
Thank you!

**Comment by NoelJacob** [comment]
Hey @RealChrisSean can I take this up?

**Comment by RealChrisSean** [comment]
@NoelJacob yes! :D

**Comment by NoelJacob** [comment]
Submitted PR: https://github.com/airbytehq/airbyte/pull/18632#issue-1427839749

**Comment by RealChrisSean** [comment]
Amazing!
