### ISSUE TITLE
New Destination: Typesense

### ISSUE THREAD

**Issue by cirdes** [airbytehq/connector-contest#155]
[Typesense](https://typesense.org/) is a modern, privacy-friendly, open source search engine built from the ground up using cutting-edge search algorithms, that take advantage of the latest advances in hardware capabilities.

It is an alternative to Elasticsearch, Algolia and Meilisearch

**Comment by RealChrisSean** [comment]
Amazing! Did you want me to assign this to you?

**Comment by cirdes** [comment]
@RealChrisSean, sure!

**Comment by cirdes** [comment]
@RealChrisSean , the PR was merged https://github.com/airbytehq/airbyte/pull/18349

**Comment by RealChrisSean** [comment]
AMAZING!!!!

**Comment by RealChrisSean** [comment]
Congrats :)

**Comment by RealChrisSean** [comment]
Closing as complete
