### ISSUE TITLE
Alternative Source: Google Ads

### ISSUE THREAD

**Issue by mutt-santiago-stachuk** [airbytehq/connector-contest#156]
## What
 Trying to replicate conector developed with Python SDK in `low code sdk`

## Why
 If performance is similar, it may be more easy to update connector for future contributors/collaborators

## OG Source Google Ads
 [Airbyte Gads documentation](https://docs.airbyte.com/integrations/sources/google-ads/)

**Comment by mutt-santiago-stachuk** [comment]
I nominate myself for this one if there's no  problem :)

**Comment by RealChrisSean** [comment]
Hi @mutt-santiago-stachuk I have assigned this issue to you. Good luck! :)

**Comment by RealChrisSean** [comment]
https://github.com/airbytehq/airbyte/pull/18091
