### ISSUE TITLE
New Source: SpaceX API

### ISSUE THREAD

**Issue by btkcodedev** [airbytehq/connector-contest#157]
https://api.spacexdata.com/v5/launches

Open Source REST API for SpaceX data.
Fully open source
Link: https://github.com/r-spacex/SpaceX-API

**Comment by btkcodedev** [comment]
I would like to work with this using low code cdk
With no auth

**Comment by btkcodedev** [comment]
V4 has couple of endpoints
But will try to give my level best

**Comment by RealChrisSean** [comment]
Hello @btkcodedev good luck. I have assigned this issue to you.

**Comment by btkcodedev** [comment]
![IMG_20221020_120104](https://user-images.githubusercontent.com/47392334/196876282-d1f86504-bdcd-4757-b10d-2d717c8f372a.jpg)
These are the tests which are failing.

**Comment by btkcodedev** [comment]
@RealChrisSean 
Minor Update: Tested endpoint launches/latest and launches/id and got connection as succeeded also read data 
![image](https://user-images.githubusercontent.com/47392334/197332222-bb944f2e-fc01-4c42-9120-8f239f4b4b21.png)

**Comment by btkcodedev** [comment]
Hello maintainers 
Please check this PR
Just one build documentation is only needed to be updated.
All the other chores for a new connector is done

🎉 https://github.com/airbytehq/airbyte/pull/18311

@RealChrisSean

**Comment by RealChrisSean** [comment]
Amazing 🎊🎉! We'll get back you sometime next week since everyone is off during the weekend :).

**Comment by btkcodedev** [comment]
@RealChrisSean Update: Successfully merged!
Thank you🎉🎉
