### ISSUE TITLE
New Source: Insightly

### ISSUE THREAD

**Issue by henriblancke** [airbytehq/connector-contest#159]
API documentation: https://api.na1.insightly.com/v3.1/#!/Overview/Introduction

**Comment by henriblancke** [comment]
Already in progress using the python CDK

**Comment by RealChrisSean** [comment]
Amazing! Good luck with this. I have assigned this issue to you :)

**Comment by RealChrisSean** [comment]
Congrats on having this merged :D

**Comment by RealChrisSean** [comment]
Closing as complete
