### ISSUE TITLE
New source: Klarna

### ISSUE THREAD

**Issue by akashpatl** [airbytehq/connector-contest#160]
Build Klarna Merchant API source connector using python cdk.

https://developers.klarna.com/api/

**Comment by akashpatl** [comment]
I want to work on this.

**Comment by RealChrisSean** [comment]
Hello @akashpatl this has been assigned to you. Good luck!

**Comment by akashpatl** [comment]
@artusiep has built this! Here is the PR

https://github.com/airbytehq/airbyte/pull/18385

**Comment by RealChrisSean** [comment]
Awesome! Thank you for the update :)
