### ISSUE TITLE
New source: Fastbill

### ISSUE THREAD

**Issue by jhammarstedt** [airbytehq/connector-contest#161]
Hi, I want to work on this using the Python CDK

API docs
https://apidocs.fastbill.com/

**Comment by jhammarstedt** [comment]
I want to work on this

**Comment by RealChrisSean** [comment]
Hello @jhammarstedt this has been asigned to you. Good luck!

**Comment by jhammarstedt** [comment]
Here's my initial draft https://github.com/airbytehq/airbyte/pull/18593 

Will work on the tests now

**Comment by RealChrisSean** [comment]
Amazing! :)

**Comment by jhammarstedt** [comment]
@RealChrisSean has been merged so we can close this😊
