### ISSUE TITLE
New Source: Xero

### ISSUE THREAD

**Issue by alkali** [airbytehq/connector-contest#164]
I would like to implement this one. I'm not sure if it's possible to make a connector for default OAuth Xero authorization (due to this issue https://github.com/airbytehq/airbyte/issues/3990), as Xero tokens are short-living and both access_token and refresh_token should be refreshed every 30 minutes. But at least I can build a connector for Xero Custom Connections, which uses a different mechanism of token refreshing.

**Comment by RealChrisSean** [comment]
Hey @alkali I will assign this to you. Good luck with this!
