### ISSUE TITLE
New Source: GoCardless

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/connector-contest#166]
https://github.com/airbytehq/airbyte/pull/17792

**Comment by RealChrisSean** [comment]
Tagging @isaacharrisholt for reference :). Congrats on having this merged :).

**Comment by RealChrisSean** [comment]
Closing as complete

**Comment by RealChrisSean** [comment]
Closing as complete

**Comment by isaacharrisholt** [comment]
Hey, just wanted to flag that this is tagged with `python cdk` when it was made with the low-code CDK :)
