### ISSUE TITLE
New Source: ActiveCampaign

### ISSUE THREAD

**Issue by dainiussa** [airbytehq/connector-contest#167]
Hi, I would like to work on this source using Low-Code CDK. API docs: https://developers.activecampaign.com/reference/overview @RealChrisSean

**Comment by RealChrisSean** [comment]
Excellent! @dainiussa this has been assigned to you

**Comment by dainiussa** [comment]
Opened a PR for this issue: https://github.com/airbytehq/airbyte/pull/18335 :)

**Comment by RealChrisSean** [comment]
Amazing! Wow that was fast! 🎊🎉😎

**Comment by RealChrisSean** [comment]
Congrats on having this merged!
