### ISSUE TITLE
New Source: StackAdapt 

### ISSUE THREAD

**Issue by pabloescoder** [airbytehq/connector-contest#168]
StackAdapt is the self-serve programmatic advertising platform used by exceptional digital marketers.

https://docs.stackadapt.com/

I saw this API in the requested connectors page of the Airbyte website. Since I have already made a PR for my previous issue (which was merged), can I start working on this as a part of the connector contest? 

I will be using the Low Code CDK for implementing this connector.

**Comment by RealChrisSean** [comment]
I have assigned this to you. Good luck!

**Comment by pabloescoder** [comment]
@RealChrisSean Thank you!

**Comment by pabloescoder** [comment]
@RealChrisSean Authorization for this API requires an API key that can be requested from the Account Manager (source: docs). So, in my opinion, it is not possible to create a personal account and get an API key, but rather an organization that already has a StackAdapt account can provide an API key to their employees. 
I've emailed the StackAdapt support team, mentioning the whole situation in detail, and asked if they could provide an account/API key with some dummy data using which I can implement and test a connector for Airbyte. It's been two days since I sent that email, but I haven't heard back. Can I put this issue on hold for now since I cannot create a personal account and get the API key?

**Comment by RealChrisSean** [comment]
Yes of course. I’m sorry to hear how difficult it is to reach them. :(

**Comment by pabloescoder** [comment]
Should I close this issue for now? I can reopen it if I get an API key/trial account from the StackAdapt team.

**Comment by RealChrisSean** [comment]
Yes, that's fine. I have closed it for you. Please let me know if you want to reopen this later.
