### ISSUE TITLE
New Source: NASA APOD

### ISSUE THREAD

**Issue by xlahuerta** [airbytehq/connector-contest#169]
I'll work on this one! (using python CDK)

**Comment by RealChrisSean** [comment]
Awesome! I have assigned this to you. Good luck :)

**Comment by xlahuerta** [comment]
PR https://github.com/airbytehq/airbyte/pull/18394

**Comment by RealChrisSean** [comment]
Amazing!

**Comment by RealChrisSean** [comment]
Congrats on having this merged!
