### ISSUE TITLE
New Source: Mailjet Mail API

### ISSUE THREAD

**Issue by haithem-souala** [airbytehq/connector-contest#170]
Hi, i would like to work on this one.

**Comment by RealChrisSean** [comment]
Awesome! I have assigned this to you. Will you be using the low-code cdk or python cdk? :)

**Comment by haithem-souala** [comment]
low-code

**Comment by haithem-souala** [comment]
PR [#[source mail](https://github.com/airbytehq/airbyte/pull/18332)](https://github.com/airbytehq/airbyte/pull/18332)

**Comment by RealChrisSean** [comment]
Amazing! Our team will get back to you within the next few days. Thank you!

**Comment by haithem-souala** [comment]
Can you please add the label hacktober :)
Thx

**Comment by RealChrisSean** [comment]
Done! :)

**Comment by haithem-souala** [comment]
PR Merged!

**Comment by RealChrisSean** [comment]
AMAZING!
