### ISSUE TITLE
New Source: Mailjet SMS API

### ISSUE THREAD

**Issue by haithem-souala** [airbytehq/connector-contest#171]
I would like to work on this one.

**Comment by RealChrisSean** [comment]
Awesome! This has been assigned to you.

**Comment by RealChrisSean** [comment]
duplicate

**Comment by haithem-souala** [comment]
Hi @RealChrisSean,
This is not a duplicate, this is another API for the same company: Mailjet, it's  2 different product:
Mail API
SMS API

**Comment by RealChrisSean** [comment]
Sorry about that @haithem-souala. I have reopened this :)

**Comment by haithem-souala** [comment]
PR: https://github.com/airbytehq/airbyte/pull/18345

**Comment by RealChrisSean** [comment]
Amazing! Our team should get back to you within a few days :)

**Comment by RealChrisSean** [comment]
Congrats on having this merged!
