### ISSUE TITLE
SFTP Bulk [Python CDK]

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/connector-contest#172]
https://github.com/airbytehq/airbyte/pull/17691

Tagging @henriblancke for reference

**Comment by RealChrisSean** [comment]
Complete

**Comment by RealChrisSean** [comment]
@henriblancke can you please update your GitHub account where it will show your email on your profile so we can send you the proper payment once we send out everyone's prizes? 

You will receive $500 for your merged PR. 

If you prefer I can also email you via Twitter to collect it. Thanks!

**Comment by henriblancke** [comment]
@RealChrisSean updated my GitHub account :) thanks!
