### ISSUE TITLE
Source: Elasticsearch

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#18]

**Comment by avaidyanatha** [comment]
@olivermeyer It's yours! Just make sure to follow along and update this issue as you make progress: https://github.com/airbytehq/airbyte/issues/2255

**Comment by janiek** [comment]
@olivermeyer do you have any update on this one?

**Comment by olivermeyer** [comment]
> @olivermeyer do you have any update on this one?

I have a working connector with most tests passing. It's only full refresh for now, which might cause performance issues when dealing with very large indexes, but I'm not sure I'll have time to implement the incremental feature before the end of the hacktober. I'll push in the next few days.

**Comment by moon03432** [comment]
@olivermeyer any updates for now?
