### ISSUE TITLE
New Source: Omnisend

### ISSUE THREAD

**Issue by dainiussa** [airbytehq/connector-contest#180]
Hi, I would like to work on this source using Low-Code CDK. API docs: https://api-docs.omnisend.com/reference/intro @RealChrisSean

**Comment by RealChrisSean** [comment]
Awesome! I have assigned this ticket to you :) good luck!

**Comment by dainiussa** [comment]
Opened a PR for this issue: https://github.com/airbytehq/airbyte/pull/18577

**Comment by RealChrisSean** [comment]
Awesome!

**Comment by dainiussa** [comment]
This PR is merged now @RealChrisSean
