### ISSUE TITLE
New Source: EmailOctopus

### ISSUE THREAD

**Issue by scottleechua** [airbytehq/connector-contest#181]
Hello! I'd like to work on this email newsletter API using the Low-code kit: https://emailoctopus.com/api-documentation @RealChrisSean :)

**Comment by RealChrisSean** [comment]
Good luck! :)

**Comment by scottleechua** [comment]
In progress on fork!

**Comment by RealChrisSean** [comment]
NICE!!!

**Comment by scottleechua** [comment]
Update -- currently on pause due to API Invalid errors -- I'm in communication with the data source to see if it's an API issue!

**Comment by RealChrisSean** [comment]
Sorry to hear that! :(

**Comment by scottleechua** [comment]
Settled issue, opened a [PR](https://github.com/airbytehq/airbyte/pull/18647) on the main repo!

**Comment by RealChrisSean** [comment]
Amazing!
