### ISSUE TITLE
New Destination: Heap Analytics

### ISSUE THREAD

**Issue by YiyangLi** [airbytehq/connector-contest#183]
## Background
[Heap Analytics](https://heap.io) is a product analytics tool that collects customer behaviors in web apps and mobile apps. With the powerful analytics tool,  [Illuminate](https://www.heap.io/platform/illuminate), people sometimes use Heap as a BI tool to analyze and visualize data. This destination connection here can import data to Heap, from various sources. 

## API Docs
https://developers.heap.io/reference/server-side-apis-overview
Data are imported via the 3 APIs -- Bulk Track, Bulk Add User Properties, Bulk Add Account Properties

I plan to use python destination cdk to build it.

**Comment by RealChrisSean** [comment]
Good luck with this!  :)

**Comment by YiyangLi** [comment]
The commit has been reverted. https://github.com/airbytehq/airbyte/pull/19357
