### ISSUE TITLE
New source - tyntec SMS

### ISSUE THREAD

**Issue by haithem-souala** [airbytehq/connector-contest#184]
HI,

I would like to work on this one: https://api.tyntec.com/reference/sms/current.html#sms-api

**Comment by haithem-souala** [comment]
Low code cdk

**Comment by RealChrisSean** [comment]
Awesome! I have assigned this issue to you. Good luck!

**Comment by haithem-souala** [comment]
The API is not well documented, and its poor.

**Comment by haithem-souala** [comment]
If anyone wanna jump on, feel welcome.

**Comment by RealChrisSean** [comment]
@btkcodedev this is up for the taking

**Comment by michizhou** [comment]
@RealChrisSean If it's alright, I would like to work on this connector. I should have a PR out tomorrow.

**Comment by btkcodedev** [comment]
I've am working with other PRs
Let @michizhou may take it, if wanted🙌

**Comment by RealChrisSean** [comment]
Done :)
