### ISSUE TITLE
New Source: The Guardian API

### ISSUE THREAD

**Issue by pabloescoder** [airbytehq/connector-contest#185]
The Guardian Open Platform is a public web service for accessing all the content the Guardian creates, categorised by tags and section.

https://open-platform.theguardian.com/documentation/

I would like to work on implementing this connector! I will be using the Low Code CDK for this.

**Comment by RealChrisSean** [comment]
Amazing! I have assigned this ticket to you.

**Comment by pabloescoder** [comment]
> Amazing! I have assigned this ticket to you.

Thank you!

**Comment by pabloescoder** [comment]
@RealChrisSean My PR for this issue has been merged successfully :D Could you please add the `completed` tag?
