### ISSUE TITLE
New Source: Alpaca 

### ISSUE THREAD

**Issue by vickywane** [airbytehq/connector-contest#186]
I would love to use the low-code CDK to create a new source for Alpaca's News API: https://alpaca.markets/docs/market-data/news/  . 

If I have more time left, I will be glad to extend the PR scope to cover other Alpaca APIs such as the [Trading](https://alpaca.markets/docs/api-references/trading-api/), [Broker](https://alpaca.markets/docs/api-references/broker-api/), and [Crypto](https://alpaca.markets/docs/api-references/crypto-api/) APIs. 

Cc: @RealChrisSean

**Comment by RealChrisSean** [comment]
Sounds good! I have assigned this to you :)

**Comment by vickywane** [comment]
@RealChrisSean I have to drop support for the News API ( https://alpaca.markets/docs/market-data/news/ ) as it returns XML formatted data and not JSON. I'll focus on other Alpaca APIs that return JSON.

**Comment by RealChrisSean** [comment]
Sounds good! Thank you for the update :)
