### ISSUE TITLE
New Source: Twilio TaskRouter

### ISSUE THREAD

**Issue by aazam-gh** [airbytehq/connector-contest#187]
I would like to work on building a connector for https://www.twilio.com/docs/taskrouter/api using the Low code SDK.

**Comment by RealChrisSean** [comment]
Hello I have assigned this ticket to you. Good luck!

**Comment by aazam-gh** [comment]
@RealChrisSean the twilio task router api unfortunately doesn't support pagination, so I wont be able to build it with the Low-Code CDK :(

**Comment by RealChrisSean** [comment]
Noooo I'm sorry about that :(

**Comment by RealChrisSean** [comment]
Will you attempt this with the python cdk? :)

**Comment by aazam-gh** [comment]
I'll give it a shot!

**Comment by RealChrisSean** [comment]
Good luck :)

**Comment by Alcadeus0** [comment]
Do all the streams need to be implemented in a separate streams.py file? Because the cdk shows that they all are declared in the source.py file but when i checked other connectors I found that its split

**Comment by aazam-gh** [comment]
@RealChrisSean  I've built the connector using the Low Code CDK !!! 
Let me know what changes need to be taken care of :)
https://github.com/airbytehq/airbyte/pull/18685

**Comment by RealChrisSean** [comment]
Amazing!

**Comment by aazam-gh** [comment]
Hey @RealChrisSean my PR was being under review by a contributor but wasn't merged yesterday. Will it still count towards the contest?
