### ISSUE TITLE
New source - Secoda

### ISSUE THREAD

**Issue by haithem-souala** [airbytehq/connector-contest#188]
Hey,

I would like to work on this: https://docs.secoda.co/secoda-api

LOW CODE CDK.

**Comment by haithem-souala** [comment]
PR: https://github.com/airbytehq/airbyte/pull/18378

**Comment by haithem-souala** [comment]
@RealChrisSean please can u add pr submitted label? thx.

**Comment by RealChrisSean** [comment]
> PR: https://github.com/airbytehq/airbyte/pull/18378

Done :)
