### ISSUE TITLE
New source - K6 Cloud

### ISSUE THREAD

**Issue by haithem-souala** [airbytehq/connector-contest#189]
Hey,

Another one https://developers.k6.io/

Low Code CDK

**Comment by RealChrisSean** [comment]
Awesome I have assigned this to you :)

**Comment by haithem-souala** [comment]
PR: https://github.com/airbytehq/airbyte/pull/18393

**Comment by RealChrisSean** [comment]
Amazing @haithem-souala how was it using our low-code cdk? Completing this in five hours is impressive :). cc @misteryeo

**Comment by haithem-souala** [comment]
low-code cdk, is awesome. a game changer, companies will save a lot of money with this.

**Comment by RealChrisSean** [comment]
That is awesome to hear!
