### ISSUE TITLE
Source: Workable

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#19]

**Comment by delenamalan** [comment]
Me please :)

**Comment by RealChrisSean** [comment]
Hi @delenamalan this has been assigned to you :D

**Comment by RealChrisSean** [comment]
Hi, @delenamalan will you use the [low-code CDK ](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/) for this? :)

**Comment by RealChrisSean** [comment]
Amazing!

**Comment by RealChrisSean** [comment]
I will re-open this and close it at the end of hacktoberfest to help me track everything. Good job with this! :)

**Comment by RealChrisSean** [comment]
Closing as complete
