### ISSUE TITLE
New Source: ConvertKit

### ISSUE THREAD

**Issue by dainiussa** [airbytehq/connector-contest#191]
Hi, I would like to work on this source using Low-Code CDK. API docs: https://developers.convertkit.com/#getting-started

**Comment by RealChrisSean** [comment]
Awesome! I have assigned this to you. Good luck :).

**Comment by dainiussa** [comment]
Opened a pull request for this issue: https://github.com/airbytehq/airbyte/pull/18455 @RealChrisSean

**Comment by RealChrisSean** [comment]
Amazing!!

**Comment by RealChrisSean** [comment]
Congrats on having this merged :)
