### ISSUE TITLE
New source : Decidim

### ISSUE THREAD

**Issue by Dynnammo** [airbytehq/connector-contest#192]
# Decidim
## Introduction
[Decidim](Decidim is a digital platform for citizen participation) is a digital platform for citizen participation.

Used by about 400 cities in the world, the project is currently supported by the City Council of Barcelona, along with some integrators throughtout the world. Repository of the RoR project can be visited here : https://github.com/decidim/decidim.

## Connector
I started making a  **Python HTTP request connector** using the documentation [here] https://docs.airbyte.com/connector-development/tutorials/cdk-tutorial-python-http/getting-started, taking advantage of the public GraphQL API of every Decidim instance in the world.

This work seems quite simple since the schema is fixed, however its purpose is also to serve as basis of the future general GraphQL connector, on which I previously discussed here : #117

**Comment by ayrotideysarkar** [comment]
Is this open? 
If yes then i want to work on it🙂

**Comment by RealChrisSean** [comment]
This is taken @ayrotideysarkar but thanks for asking first :)

**Comment by Dynnammo** [comment]
> Is this open? If yes then i want to work on itslightly_smiling_face

If you want to help out @ayrotideysarkar you can take a look on the draft PR I began here : https://github.com/airbytehq/airbyte/pull/18415
