### ISSUE TITLE
New Source - Sonar Cloud

### ISSUE THREAD

**Issue by haithem-souala** [airbytehq/connector-contest#193]
I would like to work on this: https://sonarcloud.io/

Thx

**Comment by RealChrisSean** [comment]
I have assigned this to you good luck!

**Comment by RealChrisSean** [comment]
Will you use the low-code CDK?

**Comment by haithem-souala** [comment]
Low Code CDK

**Comment by haithem-souala** [comment]
PR: https://github.com/airbytehq/airbyte/pull/18475

**Comment by RealChrisSean** [comment]
This is amazing!

**Comment by RealChrisSean** [comment]
Congrats on having this merged!
