### ISSUE TITLE
New Source - Toggl

### ISSUE THREAD

**Issue by haithem-souala** [airbytehq/connector-contest#195]
Hey, it's me again :)

I would like to work on this one: https://developers.track.toggl.com/docs/index.html

**Comment by RealChrisSean** [comment]
Awesome! I have signed this to you. Which CDK will you be using?

**Comment by haithem-souala** [comment]
Low Code CDK

**Comment by RealChrisSean** [comment]
Amazing good luck :)

**Comment by haithem-souala** [comment]
PR: https://github.com/airbytehq/airbyte/pull/18507

**Comment by RealChrisSean** [comment]
Amazing!

**Comment by marcosmarxm** [comment]
It was merged in https://github.com/airbytehq/airbyte/pull/19307
