### ISSUE TITLE
New Source : Google WebFonts

### ISSUE THREAD

**Issue by btkcodedev** [airbytehq/connector-contest#196]
I would like to work on this source, [https://webfonts.googleapis.com/v1/webfonts?key=[API_KEY]](https://webfonts.googleapis.com/v1/webfonts?key=%5BAPI_KEY%5D)'
Single endpoint but useful with destinations

**Comment by btkcodedev** [comment]
I would like to work on this source, https://webfonts.googleapis.com/v1/webfonts?key=[API_KEY]'
Single endpoint but useful with destinations

**Comment by RealChrisSean** [comment]
This has been assigned to you

**Comment by btkcodedev** [comment]
@RealChrisSean Done & Done. 
https://github.com/airbytehq/airbyte/pull/18496
Build of the connector is only left to do
Waiting for review

Thanks :)

**Comment by RealChrisSean** [comment]
Amazing!

**Comment by btkcodedev** [comment]
@RealChrisSean Update: The PR has been approved and build has been published.
Cheers!

**Comment by RealChrisSean** [comment]
Amazing!!!!!! How are you liking the low-code CDK so far?

**Comment by RealChrisSean** [comment]
I will mark this as complete as soon as your PR is merged :)

**Comment by btkcodedev** [comment]
@RealChrisSean Update: Approved & Merged!
Also Low-code CDK is amazing. Big cheers for the brains behind it.
PS: Always appreciating the efforts of @RealChrisSean & [marcosmarxm](https://github.com/marcosmarxm) for the maintainer's work, you guys are amazing.

**Comment by RealChrisSean** [comment]
This is amazing! Congrats! :)

Can you please make sure your email is visible on your profile so we can contact you once we start sending payments out?

Thank you!

**Comment by RealChrisSean** [comment]
Hey @btkcodedev is the email on your profile the same for your PayPal account? Thanks!

**Comment by btkcodedev** [comment]
@RealChrisSean Linked mail is different, I've got my paypal.me link as
https://paypal.me/btkcodedev?country.x=IN&locale.x=en_GB
Thanks!

**Comment by btkcodedev** [comment]
@RealChrisSean Do tag me here or contact me with email, for any further information
