### ISSUE TITLE
New Source - InfluxDB

### ISSUE THREAD

**Issue by bala-ceg** [airbytehq/connector-contest#199]
API Reference:
https://docs.influxdata.com/influxdb/v2.4/api-guide/tutorials/python/

**Comment by bala-ceg** [comment]
Hi @RealChrisSean, I would like to work on this one

**Comment by RealChrisSean** [comment]
Awesome I have assigned this to you. Good luck :). Which CDK will you be using?

**Comment by bala-ceg** [comment]
Thanks @RealChrisSean, I would like to attempt this using low code cdk

**Comment by RealChrisSean** [comment]
Awesome good luck :)

**Comment by bala-ceg** [comment]
@RealChrisSean Raised PR  [18801](https://github.com/airbytehq/airbyte/pull/18801) for this Issue

**Comment by RealChrisSean** [comment]
Amazing!
