### ISSUE TITLE
New Source: Firebase Realtime Database

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#20]

**Comment by koji-m** [comment]
Could you tell me which Firebase product is this Connector specifically about?
Cloud Firestore(https://firebase.google.com/products/firestore), Firebase Realtime Database(https://firebase.google.com/products/realtime-database) or something else?

**Comment by RealChrisSean** [comment]
Hi @koji-m you could potentially make a source connector for both :). You should be able to create the source connector using our new [low-code cdk](https://docs.airbyte.com/connector-development/config-based/). Did you want to give that one a try?

**Comment by sw-yx** [comment]
eventually we'll want both, but suggest starting with Realtime database as that is the older one?

- RTDB: https://firebase.google.com/docs/reference/rest/database
- Firestore: https://firebase.google.com/docs/firestore/use-rest-api

**Comment by koji-m** [comment]
Thank you for you reply. I'll work on Source Realtime Database first.

**Comment by RealChrisSean** [comment]
Good luck! :)

**Comment by itaseskii** [comment]
There is already one PR opened for a Firestore source connector which might worth looking into  https://github.com/airbytehq/airbyte/pull/15595

**Comment by koji-m** [comment]
Thank you for your advice. I'll refer it.

**Comment by RealChrisSean** [comment]
Hi @koji-m how has it been going? Anything we can help with? :)

**Comment by koji-m** [comment]
Thank you @RealChrisSean . I have just completed the minimal implementation.
