### ISSUE TITLE
New Source - Coinmarketcap

### ISSUE THREAD

**Issue by haithem-souala** [airbytehq/connector-contest#202]
Hey,

I wanna work on this one: https://coinmarketcap.com/api/

Low code cdk.

Thanks

**Comment by haithem-souala** [comment]
PR: https://github.com/airbytehq/airbyte/pull/18565

**Comment by RealChrisSean** [comment]
Amazing! You are making these connectors very fast lol. Any critiques or anything you think that could help improve the low code CDK would be very helpful :)

**Comment by haithem-souala** [comment]
LooL :)

Yeah, it would be cool, if you add to the connector template: 
* documentationUrl in spec.yaml (documentationUrl: https://docs.airbyte.com/integrations/sources/CONNECTOR_NAME)
* properties -> title in spec.yaml

**Comment by RealChrisSean** [comment]
Awesome! This has been noted :D. cc @misteryeo 

Thanks @haithem-souala :)

**Comment by haithem-souala** [comment]
Otherwise, the CDK is already stable, every time i look for something i found it.
