### ISSUE TITLE
New Source: News API

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/connector-contest#204]
@isaacharrisholt for reference. Congrats :)

**Comment by RealChrisSean** [comment]
https://github.com/airbytehq/airbyte/pull/18301

**Comment by RealChrisSean** [comment]
closing as complete

**Comment by isaacharrisholt** [comment]
Hey, just wanted to flag that this is tagged with `python-cdk` when it was made with the low code CDK :)
