### ISSUE TITLE
New Source: Newsdata

### ISSUE THREAD

**Issue by xlahuerta** [airbytehq/connector-contest#205]
I'd like to add a connector for Newsdata.io using the low-code SDK :)

https://newsdata.io/docs

**Comment by RealChrisSean** [comment]
I have assigned this to you. Good luck!

**Comment by xlahuerta** [comment]
PR https://github.com/airbytehq/airbyte/pull/18576

**Comment by RealChrisSean** [comment]
Amazing!!

**Comment by xlahuerta** [comment]
Merged! 🎉
