### ISSUE TITLE
New Source - Rocket.chat

### ISSUE THREAD

**Issue by haithem-souala** [airbytehq/connector-contest#206]
Hey,

I would like to work on this one: https://developer.rocket.chat/reference/api/rest-api

Low code cdk.

Thanks.

**Comment by RealChrisSean** [comment]
Amazing! I have assigned this to you :).

**Comment by haithem-souala** [comment]
PR: https://github.com/airbytehq/airbyte/pull/18635

**Comment by RealChrisSean** [comment]
You are way too fast at this @haithem-souala haha. Thanks for the heads up. :D
