### ISSUE TITLE
New Source: Plausible.io

### ISSUE THREAD

**Issue by scottleechua** [airbytehq/connector-contest#208]
Hello! I'd like to try using the low-code CDK to create a [Plausible Analytics](https://plausible.io/docs/stats-api) connector. :)

(P.S. the [other issue](https://github.com/airbytehq/connector-contest/issues/181) I'm working on is on hold due to API errors.)

**Comment by RealChrisSean** [comment]
Awesome! I have assigned this to you. Good luck :)

**Comment by scottleechua** [comment]
Opened a [PR](https://github.com/airbytehq/airbyte/pull/18657) for this connector!

**Comment by RealChrisSean** [comment]
Amazing!
