### ISSUE TITLE
New source: Coda 

### ISSUE THREAD

**Issue by himanshuc3** [airbytehq/connector-contest#210]
Hi, I would like to work on this source using connector for coda.
API documentation: https://coda.io/developers/apis/v1#section/Introduction

Is it up for grabs @RealChrisSean @avaidyanatha

**Comment by RealChrisSean** [comment]
Hi @himanshuc3 it is available. Will you use our Python CDK or low-code? Good luck :)

**Comment by himanshuc3** [comment]
Python CDK would serve the purpose @RealChrisSean

**Comment by RealChrisSean** [comment]
Sounds good!
