### ISSUE TITLE
New Source: Smaily

### ISSUE THREAD

**Issue by dainiussa** [airbytehq/connector-contest#213]
Hi, I would like to work on this source using Low-Code CDK. API docs: https://smaily.com/help/api @RealChrisSean

**Comment by RealChrisSean** [comment]
Amazing! I have assigned this to you. Good luck :)

**Comment by dainiussa** [comment]
Opened a PR for this: https://github.com/airbytehq/airbyte/pull/18674

**Comment by RealChrisSean** [comment]
Amazing!
