### ISSUE TITLE
New Source: Pocket

### ISSUE THREAD

**Issue by xlahuerta** [airbytehq/connector-contest#214]
I'd like to add a connector for [Pocket](https://getpocket.com/developer/docs/overview) using the low-code CDK :)

**Comment by RealChrisSean** [comment]
Awesome! Good luck :D

**Comment by xlahuerta** [comment]
PR https://github.com/airbytehq/airbyte/pull/18655

**Comment by RealChrisSean** [comment]
Amazing! :)

**Comment by xlahuerta** [comment]
Merged! 🎉
