### ISSUE TITLE
New Source - Configcat

### ISSUE THREAD

**Issue by haithem-souala** [airbytehq/connector-contest#215]
Hi,

I would like to work on this one: https://api.configcat.com/docs/#section/OpenAPI-Specification

Low code cdk.

Thanks.

**Comment by RealChrisSean** [comment]
This has been assigned to you :)

**Comment by haithem-souala** [comment]
PR: https://github.com/airbytehq/airbyte/pull/18649

**Comment by RealChrisSean** [comment]
Amazing!
