### ISSUE TITLE
Source: CrossKnowledge

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#22]

**Comment by Prodyte** [comment]
I'll work on this one.

**Comment by RealChrisSean** [comment]
Awesome! This has been assigned to you :). Good luck!

**Comment by Prodyte** [comment]
I have requested API access from crossKnowledge, it may take a few weeks. Meanwhile, can I work on another one?

**Comment by RealChrisSean** [comment]
Yes of course :). Thanks for letting us known! 🙏

**Comment by RealChrisSean** [comment]
Hi @Prodyte how has it been going? Anything we can help with?

**Comment by BajajAyush** [comment]
Please assign it to me, i am willing to give it shot

**Comment by RealChrisSean** [comment]
Hi @BajajAyush I have assigned this ticket to you. Good luck!
