### ISSUE TITLE
New Source: TVMaze Schedule

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/connector-contest#220]
https://github.com/airbytehq/airbyte/pull/18333

Merged. Reference @isaacharrisholt

**Comment by RealChrisSean** [comment]
Congrats on having this merged!

**Comment by RealChrisSean** [comment]
@isaacharrisholt can you please update your GitHub account where it will show your email on your profile so we can send you the proper payment once we sent out everyone's prizes? 

If you prefer I can also email you via Twitter to collect it. Thanks!

**Comment by isaacharrisholt** [comment]
> @isaacharrisholt can you please update your GitHub account where it will show your email on your profile so we can send you the proper payment once we sent out everyone's prizes?
> 
> If you prefer I can also email you via Twitter to collect it. Thanks!

@RealChrisSean Twitter would be better. It's @IsaacHarrisHolt. Thanks!

**Comment by isaacharrisholt** [comment]
Hey, just wanted to flag that this is tagged with `python-cdk` when it was made with the low-code CDK :)
