### ISSUE TITLE
New Source: Breezometer

### ISSUE THREAD

**Issue by sarafonseca-123** [airbytehq/connector-contest#226]
This API forecasts the pollen conditions for a given location, allowing for issuing alerts. API documentation: https://docs.breezometer.com/api-documentation/pollen-api/v2/#daily-forecast. I'd like to do this one with the low code connector :)

**Comment by sarafonseca-123** [comment]
PR: https://github.com/airbytehq/airbyte/pull/18650

**Comment by RealChrisSean** [comment]
Wow that was fast 😎
