### ISSUE TITLE
New Source: Breezometer Air quality API

### ISSUE THREAD

**Issue by sarafonseca-123** [airbytehq/connector-contest#228]
This API forecasts the hourly air quality levels for a given location. API documentation: https://docs.breezometer.com/api-documentation/air-quality-api/v2/#hourly-forecast. I'd like to do this one with the low code connector :)

**Comment by sarafonseca-123** [comment]
PR: https://github.com/airbytehq/airbyte/pull/18650

**Comment by RealChrisSean** [comment]
Amazing!
