### ISSUE TITLE
Source: Gong

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#23]

**Comment by elliottrabac** [comment]
@RealChrisSean do you still need someone to build it?

I can work on it tomorrow if needed (deadline is 2nd Nov. right?)

**Comment by RealChrisSean** [comment]
Hey! Yes please! That would be great :)

**Comment by RealChrisSean** [comment]
@elliottrabac did you plan on using the low-code cdk?

**Comment by elliottrabac** [comment]
Yes 👍

**Comment by RealChrisSean** [comment]
Amazing :)
