### ISSUE TITLE
New source: Bored API

### ISSUE THREAD

**Issue by btkcodedev** [airbytehq/connector-contest#230]
https://www.boredapi.com/documentation
Method: Low-code CDK
Just single endpoint

**Comment by btkcodedev** [comment]
@RealChrisSean I wish to take it

**Comment by btkcodedev** [comment]
I'd like to work on this

**Comment by btkcodedev** [comment]
PS: Other issues PR submitted

**Comment by RealChrisSean** [comment]
Awesome! :)

**Comment by btkcodedev** [comment]
Closing as the source ismt much useful
