### ISSUE TITLE
New source: Punk API

### ISSUE THREAD

**Issue by btkcodedev** [airbytehq/connector-contest#231]
https://punkapi.com/documentation/v2
Method: Low-code CDK
I wish to work on this

**Comment by btkcodedev** [comment]
@RealChrisSean In the hopes of assignment and to not waste time, I've started working on the api,
Very useful for various destinations as training data for ML models
Thanks! and happy weekend :)

**Comment by RealChrisSean** [comment]
Good luck!

**Comment by btkcodedev** [comment]
Update: PR submitted

**Comment by RealChrisSean** [comment]
Amazing!

**Comment by btkcodedev** [comment]
@RealChrisSean Update: PR merged successfully!
Thanks for the support
