### ISSUE TITLE
New Source: n8n

### ISSUE THREAD

**Issue by cirdes** [airbytehq/connector-contest#236]
Hi,

I'd like to add a source for [N8n](https://n8n.io/) using the low-code SDK. N8n is an extendable workflow automation tool

https://docs.n8n.io/api/

**Comment by cirdes** [comment]
This is the [PR](https://github.com/airbytehq/airbyte/pull/18745)

**Comment by RealChrisSean** [comment]
Amazing :)

**Comment by cirdes** [comment]
@RealChrisSean , merged!

https://github.com/airbytehq/airbyte/pull/18745
