### ISSUE TITLE
New Source: New York Times

### ISSUE THREAD

**Issue by xlahuerta** [airbytehq/connector-contest#239]
I'd like to add a connector for NY Times using the low-code CDK :)

[https://developer.nytimes.com](https://developer.nytimes.com/)

**Comment by RealChrisSean** [comment]
This has been assigned to you :)

**Comment by xlahuerta** [comment]
PR https://github.com/airbytehq/airbyte/pull/18746

**Comment by xlahuerta** [comment]
Merged! 🎉
