### ISSUE TITLE
New Source - Sendinblue

### ISSUE THREAD

**Issue by haithem-souala** [airbytehq/connector-contest#241]
Hi,

I woud like to work on this one: [sendinblue](https://developers.sendinblue.com/)
Low-code cdk.

Thank YOU!

**Comment by RealChrisSean** [comment]
Good luck!

**Comment by haithem-souala** [comment]
Ohhh Chris, i missed your notifications man :)

**Comment by RealChrisSean** [comment]
:D

**Comment by haithem-souala** [comment]
My last PR: https://github.com/airbytehq/airbyte/pull/18771
It was a great journey!
Thank you @RealChrisSean !

**Comment by RealChrisSean** [comment]
AMAZING! You made a lot of connectors haha.
