### ISSUE TITLE
New connector: senseforce.io

### ISSUE THREAD

**Issue by andnig** [airbytehq/connector-contest#244]
Hey,

I'd like to work on https://senseforce.io/?lang=en
Senseforce provides a quite nice solution for Industrial IoT. 
Export IoT Data to Data Warehouses seem to be a nice use case for Senseforce users. 

Lowcode CDK

Can I work on that?

**Comment by RealChrisSean** [comment]
This has been assigned to you :)

**Comment by andnig** [comment]
Hey, 
I added a PR for that issue. Just in time I hope :-) [#18775](https://github.com/airbytehq/airbyte/pull/18775)
Also added two issues, I couldn't find any open/closed issues which might be related. If they are not relevant, let me know.
- [#18769](https://github.com/airbytehq/airbyte/issues/18769)
- [#18767](https://github.com/airbytehq/airbyte/issues/18767)

Somewhere I read we need to make sure to label the PRs/Issue with "hacktober" or "hacktoberfest". I guess this is done by you, right?

**Comment by andnig** [comment]
One question actually: How can I provide you the credentials for the sandbox account?

**Comment by RealChrisSean** [comment]
> Hey, I added a PR for that issue. Just in time I hope :-) [#18775](https://github.com/airbytehq/airbyte/pull/18775) Also added two issues, I couldn't find any open/closed issues which might be related. If they are not relevant, let me know.
> 
> * [#18769](https://github.com/airbytehq/airbyte/issues/18769)
> * [#18767](https://github.com/airbytehq/airbyte/issues/18767)
> 
> Somewhere I read we need to make sure to label the PRs/Issue with "hacktober" or "hacktoberfest". I guess this is done by you, right?

Yup its done by me :)

**Comment by RealChrisSean** [comment]
> One question actually: How can I provide you the credentials for the sandbox account?

You do this in the airbyte main repo account
