### ISSUE TITLE
New Source: Twitter

### ISSUE THREAD

**Issue by bala-ceg** [airbytehq/connector-contest#245]
https://developer.twitter.com/en/docs/twitter-api
Method: Low code CDK

**Comment by bala-ceg** [comment]
@RealChrisSean I would like to work on this

**Comment by RealChrisSean** [comment]
Hi I have assigned this to you.

**Comment by bala-ceg** [comment]
PR #18863 is submitted for this connector issue

**Comment by bala-ceg** [comment]
@RealChrisSean  PR merged for this connector
Thanks!
