### ISSUE TITLE
New Source: Grafana

### ISSUE THREAD

**Issue by bala-ceg** [airbytehq/connector-contest#246]
https://grafana.com/docs/grafana/v9.0/developers/http_api/
Method: Low code CDK

**Comment by bala-ceg** [comment]
@RealChrisSean I would like to work on this

**Comment by RealChrisSean** [comment]
Awesome I have assigned this to you. :)

**Comment by bala-ceg** [comment]
PR submitted: https://github.com/airbytehq/airbyte/pull/18858
