### ISSUE TITLE
New Source : Quotes API

### ISSUE THREAD

**Issue by Harshil0512** [airbytehq/connector-contest#249]
I would like to work on connector for Quotes API .
Link : https://type.fit/api/quotes

**Comment by Harshil0512** [comment]
Please Review My PR 

https://github.com/airbytehq/airbyte/pull/18768

**Comment by RealChrisSean** [comment]
Hello @Harshil0512 we will have to reject this as this source will not be as helpful to the community. Thank you for putting the time to create this.
