### ISSUE TITLE
Source: Adyen

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#25]

**Comment by RealChrisSean** [comment]
Hello, @NightHack36 that has been assigned to you. Good luck!

**Comment by RealChrisSean** [comment]
Hi, @NightHack36 how is this going so far? Please let me know if there's anything we can assist you with.

By the way, will you be using the [low-code CDK ](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/) for this? :)

**Comment by jhammarstedt** [comment]
@RealChrisSean Would it be possible to still do the low-code CDK for this one as part of the hackathon?

**Comment by RealChrisSean** [comment]
Yes, you can. As long as you submit a PR by 11:59 pm PST 11/02/22. :)

**Comment by RealChrisSean** [comment]
@jhammarstedt I have assigned this issue to you.

**Comment by jhammarstedt** [comment]
@RealChrisSean, I looked into this and it will be hard to get the demo account before the deadline. I'll drop from this one and work on something else instead :)
