### ISSUE TITLE
🎉New Source: Postmarkapp

### ISSUE THREAD

**Issue by jhammarstedt** [airbytehq/connector-contest#251]
Hi, I saw that this was [requested](https://airbyte.com/connector-requests) so would like to work on this one. I'll build it with Low-code CDK :)

**Comment by RealChrisSean** [comment]
Yes go for it! :)

**Comment by jhammarstedt** [comment]
@RealChrisSean 
Great! 
I created a draft PR where I added the main streams, but I want to learn more about the low-code CDK and had some questions how I can extend this further. Would you have time to look at the questions I put in the comment there? :)

Link to draft PR: https://github.com/airbytehq/airbyte/pull/18820

**Comment by RealChrisSean** [comment]
Awesome :). Our team will add that to the list and get back to you asap :)

**Comment by jhammarstedt** [comment]
@RealChrisSean has been merged so we can close this😊
