### ISSUE TITLE
New Source : Jokes API

### ISSUE THREAD

**Issue by neelshah2409** [airbytehq/connector-contest#252]
https://sv443.net/jokeapi/v2/
Wanted to make a connector for it .

**Comment by RealChrisSean** [comment]
Hello @neelshah2409 unfortunately we cannot accept this as a connector. Thanks for creating this issue and hope you can find another one soon before the deadline :).

**Comment by neelshah2409** [comment]
> Hello @neelshah2409 unfortunately we cannot accept this as a connector. Thanks for creating this issue and hope you can find another one soon before the deadline :).

Thank You and sincere apology of not getting the standard one , I would try to make another one as soon as possible.
