### ISSUE TITLE
🎉New Source: Copper 

### ISSUE THREAD

**Issue by akashpatl** [airbytehq/connector-contest#254]
New Python  CDK source for [Copper](https://copper.com/), [a requested Airbyte connector ](https://airbyte.com/connector-requests)

**Comment by akashpatl** [comment]
Hi I'd like to develop this source! :D

**Comment by akashpatl** [comment]
[Link to issue](https://github.com/airbytehq/connector-contest/issues/254)

**Comment by RealChrisSean** [comment]
Amazing!
