### ISSUE TITLE
New source: HiBob

### ISSUE THREAD

**Issue by imrehg** [airbytehq/connector-contest#259]
HiBob is an HR platform, and much of the information (though not all) is accessible through [an API](https://apidocs.hibob.com/docs/getting-started).

**Comment by hridaya423** [comment]
Hi, @imrehg do you want to work on this?
If not, I could start working on this

**Comment by RealChrisSean** [comment]
Hi @imrehg unfortunately, we will need to refuse this issue. Ty!
