### ISSUE TITLE
New Source : Polygon-Stocks-API

### ISSUE THREAD

**Issue by Harshil0512** [airbytehq/connector-contest#261]
I want to implement polygon.io's API as they provide following results : 

results (array) :
[
  c (number) :The close price for the symbol in the given time period.
  h (number) : The highest price for the symbol in the given time period.
  l (number) : The lowest price for the symbol in the given time period.
  n (integer) : The number of transactions in the aggregate window.
  o (number) : The open price for the symbol in the given time period.
  otc (boolean) : Whether or not this aggregate is for an OTC ticker. This field will be left off if false.
  t (integer) : The Unix Msec timestamp for the start of the aggregate window.
  v (number) : The trading volume of the symbol in the given time period.
  vw (number) : The volume weighted average price.
]

and other details about the stock

**Comment by Harshil0512** [comment]
PR related to this issue : 

https://github.com/airbytehq/airbyte/pull/18842

**Comment by Harshil0512** [comment]
Hello @RealChrisSean  As this PR is merged and it was part of Hacktoberfest when will I get my reward ?

**Comment by RealChrisSean** [comment]
Did you fill out the form? :)

**Comment by Harshil0512** [comment]
Which form?

**Comment by Harshil0512** [comment]
I didn't get any form @RealChrisSean

**Comment by RealChrisSean** [comment]
Are you in slack? 

https://airbytehq.slack.com/archives/C0450PCSDB2/p1669851753037349

**Comment by Harshil0512** [comment]
No I don't because I don't have airbyte workspace email to join this slack

**Comment by Harshil0512** [comment]
@RealChrisSean Please help me through this

**Comment by RealChrisSean** [comment]
No worries I got you :)

Can you please email me. I will send you a link to fill out the form. 

Chris.sean@airbyte.io 

Please paste the link to this issue in the email as well so I can verify it's you.

**Comment by Harshil0512** [comment]
I just mailed you @RealChrisSean
