### ISSUE TITLE
New Source: Aha

### ISSUE THREAD

**Issue by bala-ceg** [airbytehq/connector-contest#263]
Documentation: https://www.aha.io/api/

I would like to work on this issue.

**Comment by bala-ceg** [comment]
Apologies for last minute PR

PR Raised for the Feature: https://github.com/airbytehq/airbyte/pull/18893

**Comment by bala-ceg** [comment]
@RealChrisSean The connector issue PR is merged

**Comment by RealChrisSean** [comment]
Hey @bala-ceg awesome! Which cdk did you use? :)

**Comment by RealChrisSean** [comment]
I figured it out. Congrats :D

**Comment by bala-ceg** [comment]
Thanks @RealChrisSean for the help
