### ISSUE TITLE
New Source: Pagerduty

### ISSUE THREAD

**Issue by mmolimar** [airbytehq/connector-contest#264]
Hey!

I'd like to start building a source connector for [Pagerduty](https://developer.pagerduty.com).

There is already a connector for PD from [Faros AI](https://github.com/faros-ai/airbyte-connectors/tree/main/sources/pagerduty-source) but it implements a few entities using the CDK for Javascript/Typescript and I'd like to add a few more with the low-code CDK.

**Comment by RealChrisSean** [comment]
Hello, hacktoberfest has ended. Ty though.
