### ISSUE TITLE
Destination: AppsFlyer

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#29]

**Comment by NightHack36** [comment]
can you assign me please

**Comment by RealChrisSean** [comment]
Hello @NightHack36, I have assigned another ticket to you. Please work on only one connector at a time :D.

**Comment by kitrakrev** [comment]
Can you assign this to me?

**Comment by RealChrisSean** [comment]
Hi @kitrak-rev this has been assigned to you :)
