### ISSUE TITLE
Source: Salesforce Marketing Cloud

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#3]

**Comment by michizhou** [comment]
Hi @RealChrisSean, would it be alright if I take on this issue?

**Comment by RealChrisSean** [comment]
Hi @michizhou sorry for the late reply. Go for it! :D

**Comment by RealChrisSean** [comment]
Hi @michizhou how are things going? Anything we can help with? :)

**Comment by michizhou** [comment]
@RealChrisSean I'm still working on it right now, but I'll let you know if I have any questions or need any guidance!

**Comment by RealChrisSean** [comment]
Awesome good luck! :)

**Comment by michizhou** [comment]
@RealChrisSean I ran into some issues during the course of my connector work. I sent some messages to you via Slack with further details. I would appreciate it if you can provide any guidance or assistance. Thanks!
