### ISSUE TITLE
Source: Google My Business

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#47]

**Comment by koconder** [comment]
I'll take this one

**Comment by RealChrisSean** [comment]
@koconder please remember that you only allowed to work on one connector at a time :).

**Comment by koconder** [comment]
@RealChrisSean I’ll remove myself from the others. The Genesys one is done so I’ll only make sure I’m active on one and the others iI’ll remove. Sorry about this.

**Comment by koconder** [comment]
@RealChrisSean I’ll work on this one next. I’ll drop the other ones.

**Comment by RealChrisSean** [comment]
Hey @koconder how have things been going with this one? Anything we can help with? :)
