### ISSUE TITLE
Source: Genesys

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#48]

**Comment by koconder** [comment]
I'll take this one :)

**Comment by rhaegar2803** [comment]
@koconder the hacktoberfest [guidelines](https://github.com/airbytehq/connector-contest/blob/main/GUIDELINES.md) are stating that you can only be working on one connector at a time. Please consider self-assigning issues one at a time in order to not block multiple issues at the same time.

**Comment by koconder** [comment]
PR pending review, submitted. Jumping on the next connector. @rhaegar2803 I’ll be conscious of this. Appologies
