### ISSUE TITLE
Source: CleverTap

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#49]

**Comment by Rahul-Kumar-prog** [comment]
Hello i would like to work on this

**Comment by RealChrisSean** [comment]
Hello @Rahul-Kumar-prog this has been assigned to you :D

**Comment by RealChrisSean** [comment]
Hi @Rahul-Kumar-prog how have things been going? Anything we can help with? :)

**Comment by Rahul-Kumar-prog** [comment]
yeah sorry for the late response but i am facing an issue. actually i dont able to get clevertap api i am requesting for api key to clevertap. i think clevertap api available for corporate employee only. i am talking to clevertap person. 
if you can help me with i am grateful to you for this
