### ISSUE TITLE
Source: Uber Eats

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#53]

**Comment by Azanul** [comment]
I'd like to work on this

**Comment by RealChrisSean** [comment]
This has been assigned to you :)

**Comment by RealChrisSean** [comment]
Hi @Azanul how have things been going? Anything we can help with? :)

**Comment by Azanul** [comment]
@RealChrisSean I'm getting familiar with the python cdk. I'll surely reach out to you in case I need any help.

**Comment by RealChrisSean** [comment]
I'm happy to hear that. We're always here to help. Good luck!

**Comment by Azanul** [comment]
I won't be able to complete this on time, I still haven't received the test account I requested from Uber.

**Comment by RealChrisSean** [comment]
Sorry to hear that :(
