### ISSUE TITLE
Source: Coda

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#57]

**Comment by Garrettjson** [comment]
I'll take it

**Comment by avaidyanatha** [comment]
Hey @Garrettjson, it's yours! Make sure to follow along with this issue: https://github.com/airbytehq/airbyte/issues/2167 and give updates there once you finish.

**Comment by Garrettjson** [comment]
> Hey @Garrettjson, it would be awesome if we could get a quick project update on this one!

@avaidyanatha Still a work in progress. Got stuck, but I'll be taking a look through some of the other PRs to unblock myself. I have some time blocked this week to work on this.

**Comment by avaidyanatha** [comment]
@Garrettjson Cool, sounds good, thanks for the update - let us know in #connector-development on the Slack if you run into any blockers!

**Comment by RealChrisSean** [comment]
Not low-code compatible
