### ISSUE TITLE
Source: SAP

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#6]

**Comment by delenamalan** [comment]
Any specific SAP APIs you're looking to target?

**Comment by RealChrisSean** [comment]
Up to you :D @delenamalan

**Comment by delenamalan** [comment]
Thank @RealChrisSean, but I'd rather work on #19 for now please :)

**Comment by RealChrisSean** [comment]
Noted! :)

**Comment by RealChrisSean** [comment]
Hi, @delenamalan whenever you get back to this, will you use the [low-code CDK ](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/)? :)

**Comment by Sid-Lais** [comment]
I'm interesting in this but I'm a beginner. Are the video tutorials enough? Also where can I get the API key?

**Comment by Sid-Lais** [comment]
Got the API key and everything is set up. Should I start working on it? @avaidyanatha @RealChrisSean

**Comment by RealChrisSean** [comment]
Yes! This has been assigned to you :)

**Comment by RealChrisSean** [comment]
You can find tutorials here https://github.com/airbytehq/connector-contest

**Comment by Sid-Lais** [comment]
@RealChrisSean @avaidyanatha  You can close this issue as it has been merged.
