### ISSUE TITLE
Source: Generic Zipped Files

### ISSUE THREAD

**Issue by vagrantism** [airbytehq/connector-contest#63]
Similar to `source-file` but instead takes a single zip/tar file containing multiple files and emits each file as a stream.

**Comment by vagrantism** [comment]
I'll work on this one!

**Comment by avaidyanatha** [comment]
@sherifnada Should we integrate this into `source-file` or should it live on its own?

**Comment by vagrantism** [comment]
Hey guys, I refactored the code to extend `source-file` instead of creating a new source as you asked. Can you please see if it is good for a PR? (Haven't added tests because the `source-files` connector [requires access to some cloud providers](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/source-file#necessary-credentials-for-tests) ). However, I have built and tested it locally and it works as expected.

Github: https://github.com/vagrantism/airbyte

Here's a sample file to try out (the one I have been using) : https://static.crunchbase.com/data_crunchbase/bulk_export_sample.tar.gz

**Comment by avaidyanatha** [comment]
Hey @marcosmarxm can you take a quick look here at @vagrantism's fork to see if this is good to submit?

**Comment by vagrantism** [comment]
Hey guys, any news? I want to get started on another connector too! :)

**Comment by marcosmarxm** [comment]
@vagrantism please submit the PR in the main project so we can review/advise you.
Did you add this file to test your connector?

**Comment by vagrantism** [comment]
Done! https://github.com/airbytehq/airbyte/pull/7705
I haven't added the file, but i used it for testing the connector.
