### ISSUE TITLE
Source: Vertica

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#8]

**Comment by MinuraPunchihewa** [comment]
Hey @avaidyanatha, I would love to work on this issue!

**Comment by RealChrisSean** [comment]
@MinuraPunchihewa go for it :)

**Comment by RealChrisSean** [comment]
Hi @MinuraPunchihewa how have things been going? Anything we can help you with?

**Comment by MinuraPunchihewa** [comment]
Hey @RealChrisSean, I am in the process of working on this. I have opened a draft PR after working on it a little. The community has said that they will help me out.

**Comment by RealChrisSean** [comment]
Excellent! :)

**Comment by RealChrisSean** [comment]
https://github.com/airbytehq/airbyte/pull/17886
