### ISSUE TITLE
Source: xkcd

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#89]
https://xkcd.com/json.html

**Comment by sarafonseca-123** [comment]
I would like to work on this one!

**Comment by RealChrisSean** [comment]
@sarafonseca-123 itis yours :)

**Comment by RealChrisSean** [comment]
Hi @sarafonseca-123 how is this going? Anything we can help with?

**Comment by sarafonseca-123** [comment]
Hi @RealChrisSean! I got caught up with some things at work, but I'm planning to open a PR on this issue by Sunday

**Comment by RealChrisSean** [comment]
This is amazing! Thank you for the update @sarafonseca-123 :)

I will label this with "pr submitted" so I can make sure to follow up with this by next weekend :).

**Comment by sarafonseca-123** [comment]
@RealChrisSean Since the PR was merged, can this issue be closed now?

**Comment by RealChrisSean** [comment]
Hi @sarafonseca-123 I will close all of the issues a week or so after Hacktoberfest to help me track everything and make sure everyone gets paid :)

Btw! Congrats on having your PR merged :).

**Comment by sarafonseca-123** [comment]
Thanks! 
> I will close all of the issues a week or so after Hacktoberfest

So I will take down the closing command from the [RD Station PR](https://github.com/airbytehq/airbyte/pull/18348) 😱

**Comment by RealChrisSean** [comment]
Closing as complete
