### ISSUE TITLE
Source: Wikipedia

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#90]
https://wikitech.wikimedia.org/wiki/Analytics/AQS/Pageviews

**Comment by ameyabapat-bsft** [comment]
I will work on it.

**Comment by ameyabap** [comment]
I will work on it.

**Comment by avaidyanatha** [comment]
It's yours @ameyabap!

**Comment by evwltrs** [comment]
I'll take this :). Confirm it's just for the page views endpoint?

**Comment by RealChrisSean** [comment]
@evwltrs yup :)

**Comment by RealChrisSean** [comment]
Hi @evwltrs how is this going? Anything we can help with?

**Comment by evwltrs** [comment]
> Hi @evwltrs how is this going? Anything we can help with?

It's going well, just stuck in a bit of a roadblock with something. Asked on slack yesterday and reposted it today

**Comment by btkcodedev** [comment]
@RealChrisSean If the assignee is busy, can I work on this issue?

**Comment by evwltrs** [comment]
> @RealChrisSean If the assignee is busy, can I work on this issue?

Hi, I have pretty much finished the connector there is a pull request already open :D

**Comment by RealChrisSean** [comment]
Amazing!!!

**Comment by RealChrisSean** [comment]
Can you please link to the PR here? :)

**Comment by RealChrisSean** [comment]
https://github.com/airbytehq/airbyte/pull/18343

**Comment by evwltrs** [comment]
@RealChrisSean even if the team dont find time to review before the end of october, since it's locked in does that mean I am still eligible for the bounty?

**Comment by RealChrisSean** [comment]
As long as your PR is submitted and you fix any issues after the 11/2
deadline you’ll be good to go! So yes your are. :)
