### ISSUE TITLE
Source: Public APIs

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#91]
https://api.publicapis.org/

It's a bit meta...

**Comment by andresbravog** [comment]
I can take this one, seems like a simple 2-4 endpoints with no authentication source right? Maybe a good use case for the Low code CDK.

**Comment by RealChrisSean** [comment]
This has been assigned to you :)

**Comment by RealChrisSean** [comment]
Hi @andresbravog how is this going? Anything we can help with?

**Comment by andresbravog** [comment]
@RealChrisSean looking good so far I just need to find time to complete things.

<img width="1632" alt="image" src="https://user-images.githubusercontent.com/363321/196052947-1f3ba82b-5e91-49ae-bb0e-1c0f59b037a7.png">

**Comment by btkcodedev** [comment]
@RealChrisSean If the assignee is busy, can I work on this issue?

**Comment by RealChrisSean** [comment]
Hey @andresbravog hows it going? Could @btkcodedev takeover in case things got busy for you?

**Comment by RealChrisSean** [comment]
@btkcodedev with the deadline looming, in case he doesn't get a chance to respond to us in 24hrs you can takeover :)

**Comment by andresbravog** [comment]
@RealChrisSean I'd like to finish if possible.

When is the deadline?

I'm currently blocked by https://github.com/airbytehq/airbyte/issues/17957 , but planning to have a look at it. I'll push my code.

**Comment by btkcodedev** [comment]
Okay. If it is blocked, then I would like a chance to hit on that with different cdk.
Please reply if that is okay for @andresbravog.

**Comment by andresbravog** [comment]
@btkcodedev sorry if my answer was not clear here, if I have a choice I'd like to give it a try and fix the blocker, if I don't you are good to go.

**Comment by btkcodedev** [comment]
@andresbravog  Cheers, fine then, Please give it a try with a specified time schedule as of the deadline approaching.

**Comment by btkcodedev** [comment]
@andresbravog I think I Could help in the issue with yaml file. Can we form a team for this connector development? will try to resolve the issue if possible. Expecting your reply

**Comment by andresbravog** [comment]
Thanks for the offer @btkcodedev , I think I have everything under control now!

**Comment by RealChrisSean** [comment]
:D
